CREATE TABLE `user_history` (
  `USER_HISTORY_ID` int NOT NULL AUTO_INCREMENT,
  `USER_ID` int NOT NULL,
  `MODULE` varchar(45) DEFAULT NULL,
  `SCREEN_NAME` varchar(45) NOT NULL,
  `ACTION` varchar(100) DEFAULT NULL,
  `CREATION_TS` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`USER_HISTORY_ID`),
  KEY `FK_USER_HISTORY_USER_ID` (`USER_ID`),
  CONSTRAINT `FK_USER_HISTORY_USER_ID` FOREIGN KEY (`USER_ID`) REFERENCES `employee` (`EMPLOYEE_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;