
DROP TABLE IF EXISTS `company_terms_and_conditions`;

CREATE TABLE `company_terms_and_conditions` (
  `COMPANY_TERMS_AND_CONDITIONS_ID` int(11) NOT NULL AUTO_INCREMENT,
  `TERMS_AND_CONDITIONS` text CHARACTER SET latin1 COLLATE latin1_swedish_ci,
  `CREATION_TS` timestamp NULL DEFAULT NULL,
  `CREATION_USER_ID` varchar(50) DEFAULT NULL,
  `LAST_UPDATE_TS` timestamp NULL DEFAULT NULL,
  `LAST_UPDATE_USER_ID` varchar(50) DEFAULT NULL,
  `ACTIVE_S` char(1) CHARACTER SET latin1 COLLATE latin1_swedish_ci DEFAULT 'Y',
  PRIMARY KEY (`COMPANY_TERMS_AND_CONDITIONS_ID`)
) ;

DROP TABLE IF EXISTS `country_lookup`;

CREATE TABLE `country_lookup` (
  `COUNTRY_ID` int(11) NOT NULL AUTO_INCREMENT,
  `AUDIT_ID` int(11) DEFAULT NULL,
  `COUNTRY_CD` varchar(10) DEFAULT NULL,
  `COUNTRY_NM` varchar(50) DEFAULT NULL,
  `CREATION_TS` timestamp NULL DEFAULT NULL,
  `CREATION_USER_ID` varchar(50) DEFAULT NULL,
  `LAST_UPDATE_TS` timestamp NULL DEFAULT NULL,
  `LAST_UPDATE_USER_ID` varchar(50) DEFAULT NULL,
  PRIMARY KEY (`COUNTRY_ID`)
) ;


DROP TABLE IF EXISTS `customer`;

CREATE TABLE `customer` (
  `CUSTOMER_ID` int(11) NOT NULL AUTO_INCREMENT,
  `PHONE_NBR` varchar(20) DEFAULT NULL,
  `FIRST_NM` varchar(50) NOT NULL,
  `LAST_NM` varchar(50) NOT NULL,
  `GENDER_CD` char(1) DEFAULT NULL,
  `DOB_DT` date DEFAULT NULL,
  `EMAIL_ID` varchar(50) DEFAULT NULL,
  `ADDRESS_LINE1` varchar(250) DEFAULT NULL,
  `ADDRESS_LINE2` varchar(250) DEFAULT NULL,
  `CITY_NM` varchar(50) DEFAULT NULL,
  `PIN_CD` varchar(20) DEFAULT NULL,
  `CREATION_TS` timestamp NULL DEFAULT NULL,
  `CREATION_USER_ID` varchar(50) DEFAULT NULL,
  `LAST_UPDATE_TS` timestamp NULL DEFAULT NULL,
  `LAST_UPDATE_USER_ID` varchar(50) DEFAULT NULL,
  `AUDIT_ID` int(11) DEFAULT NULL,
  `ACTIVE_S` char(1) CHARACTER SET latin1 COLLATE latin1_swedish_ci DEFAULT 'Y',
  `COUNTRY_ID` int(11) DEFAULT NULL,
  `PROVINCES_ID` int(11) DEFAULT NULL,
  `CREDIT_LIMIT` float DEFAULT NULL,
  `DISCOUNT_PERCENTAGE` float DEFAULT NULL,
  `DISCOUNT_AMOUNT` float DEFAULT NULL,
  `CREDIT_DAYS` float DEFAULT NULL,
  `ORGANISATION` varchar(50) DEFAULT NULL,
  `CUSTOMER_INSURANCE_ID` int(11) DEFAULT NULL,
  `CUSTOMER_MEMBERSHIP_ID` int(11) DEFAULT NULL,
  `PHARMACY_ID` int(11) DEFAULT NULL,
  PRIMARY KEY (`CUSTOMER_ID`),
  KEY `FK_CUSTOMER_COUNTRY_LOOKUP` (`COUNTRY_ID`),
  KEY `FK_CUSTOMER_PROVINCES_LOOKUP` (`PROVINCES_ID`),
  KEY `FK_CUSTOMER_CUSTOMER_MEMBERSHIP` (`CUSTOMER_MEMBERSHIP_ID`),
  KEY `FK_CUSTOMER_CUSTOMER_INSURANCE` (`CUSTOMER_INSURANCE_ID`),
  CONSTRAINT `FK_CUSTOMER_COUNTRY_LOOKUP` FOREIGN KEY (`COUNTRY_ID`) REFERENCES `country_lookup` (`COUNTRY_ID`) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT `FK_CUSTOMER_CUSTOMER_INSURANCE_LOOKUP` FOREIGN KEY (`CUSTOMER_INSURANCE_ID`) REFERENCES `customer_insurance` (`CUSTOMER_INSURANCE_ID`) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT `FK_CUSTOMER_CUSTOMER_MEMBERSHIP_LOOKUP` FOREIGN KEY (`CUSTOMER_MEMBERSHIP_ID`) REFERENCES `customer_membership` (`CUSTOMER_MEMBERSHIP_ID`) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT `FK_CUSTOMER_PROVINCES_LOOKUP` FOREIGN KEY (`PROVINCES_ID`) REFERENCES `provinces_lookup` (`PROVINCES_ID`) ON DELETE RESTRICT ON UPDATE RESTRICT
);


DROP TABLE IF EXISTS `customer_insurance`;

CREATE TABLE `customer_insurance` (
  `CUSTOMER_INSURANCE_ID` int(11) NOT NULL AUTO_INCREMENT,
  `CUSTOMER_ID` int(11) DEFAULT NULL,
  `INSURANCE_POLICY_ID` int(11) DEFAULT NULL,
  `INSURANCE_POLICY_CODE` varchar(100) DEFAULT NULL,
  `INSURANCE_POLICY_START` date DEFAULT NULL,
  `INSURANCE_POLICY_END` date DEFAULT NULL,
  `INSURANCE_DURATION_IN_MONTHS` int(11) DEFAULT NULL,
  `INSURANCE_PERCENTAGE_COVERAGE` float DEFAULT NULL,
  `INSURANCE_AMOUNT_LIMIT` float DEFAULT NULL,
  PRIMARY KEY (`CUSTOMER_INSURANCE_ID`),
  KEY `FK_CUSTOMER_INSURANCE` (`INSURANCE_POLICY_ID`),
  KEY `FK_CUSINS_CUSTOMER` (`CUSTOMER_ID`),
  CONSTRAINT `FK_CUSINS_CUSTOMER` FOREIGN KEY (`CUSTOMER_ID`) REFERENCES `customer` (`CUSTOMER_ID`) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT `FK_CUSTOMER_INSURANCE` FOREIGN KEY (`INSURANCE_POLICY_ID`) REFERENCES `insurance` (`INSURANCE_POLICY_ID`) ON DELETE RESTRICT ON UPDATE RESTRICT
) ;




DROP TABLE IF EXISTS `customer_membership`;

CREATE TABLE `customer_membership` (
  `CUSTOMER_MEMBERSHIP_ID` int(11) NOT NULL AUTO_INCREMENT,
  `CUSTOMER_ID` int(11) DEFAULT NULL,
  `MEMBERSHIP_CARD_ID` int(11) DEFAULT NULL,
  `CUSTOMER_NAME` varchar(50) DEFAULT NULL,
  `MEMBERSHIP_START_DATE` date DEFAULT NULL,
  `MEMBERSHIP_END_DATE` date DEFAULT NULL,
  `MEMBERSHIP_DURATION_IN_MONTHS` int(11) DEFAULT NULL,
  `MEMBERSHIP_CREDIT_LIMIT` float DEFAULT NULL,
  `MEMBERSHIP_DISCOUNT_PERCENTAGE` float DEFAULT NULL,
  `MEMBERSHIP_DISCOUNT_AMOUNT` float DEFAULT NULL,
  `MEMBERSHIP_CREDIT_DAYS` float DEFAULT NULL,
  PRIMARY KEY (`CUSTOMER_MEMBERSHIP_ID`),
  KEY `FK_CUSTOMER_MEMBERSHIP` (`MEMBERSHIP_CARD_ID`),
  KEY `FK_CUSMEM_CUSTOMER` (`CUSTOMER_ID`),
  CONSTRAINT `FK_CUSMEM_CUSTOMER` FOREIGN KEY (`CUSTOMER_ID`) REFERENCES `customer` (`CUSTOMER_ID`) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT `FK_CUSTOMER_MEMBERSHIP` FOREIGN KEY (`MEMBERSHIP_CARD_ID`) REFERENCES `membership` (`MEMBERSHIP_CARD_ID`) ON DELETE RESTRICT ON UPDATE RESTRICT
) ;


DROP TABLE IF EXISTS `delivery_types`;

CREATE TABLE `delivery_types` (
  `DELIVERY_TYPE_ID` int(11) NOT NULL AUTO_INCREMENT,
  `TYPE` varchar(50) DEFAULT NULL,
  PRIMARY KEY (`DELIVERY_TYPE_ID`)
);


DROP TABLE IF EXISTS `supplier`;

CREATE TABLE `supplier` (
  `SUPPLIER_ID` int(11) NOT NULL AUTO_INCREMENT,
  `NAME` varchar(100) DEFAULT NULL,
  `LICENSE` varchar(100) DEFAULT NULL,
  `PHONE_NBR` varchar(20) DEFAULT NULL,
  `EMAIL_ID` varchar(50) DEFAULT NULL,
  `CREATION_TS` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `CREATION_USER_ID` varchar(50) DEFAULT NULL,
  `LAST_UPDATE_TS` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00',
  `LAST_UPDATE_USER_ID` varchar(50) DEFAULT NULL,
  `ACTIVE_S` char(1) CHARACTER SET latin1 COLLATE latin1_swedish_ci DEFAULT 'Y',
  `FAX` varchar(20) DEFAULT NULL,
  `CONTACT_PERSON_EMAIL_ID` varchar(50) DEFAULT NULL,
  `CONTACT_PERSON_PHONE_NBR` varchar(20) DEFAULT NULL,
  `CONTACT_PERSON_FIRST_NM` varchar(50) DEFAULT NULL,
  `WEBSITE` varchar(500) DEFAULT NULL,
  `ADDRESS_LINE1` varchar(250) DEFAULT NULL,
  `ADDRESS_LINE2` varchar(250) DEFAULT NULL,
  `CITY_NM` varchar(50) DEFAULT NULL,
  `ZIP_CD` varchar(10) DEFAULT NULL,
  `PAYMENT_TERMS` text,
  `PAYMENT_CREDIT_NET_DAYS` int(11) DEFAULT NULL,
  `LATE_PAYMENT_INTEREST` int(11) DEFAULT NULL,
  `PIN_NO` varchar(20) DEFAULT NULL,
  `SL_NO` varchar(20) DEFAULT NULL,
  `CST_NO` varchar(20) DEFAULT NULL,
  `ALLOW_ONLINE_ORDERS` char(1) DEFAULT NULL,
  `ALLOW_MANUAL_ORDERS` char(1) DEFAULT NULL,
  `ALLOW_PHONE_ORDERS` char(1) DEFAULT NULL,
  `ACCEPT_EXPIRY_RETURNS` char(1) DEFAULT NULL,
  `ACCEPT_DAMAGED_RETURNS` char(1) DEFAULT NULL,
  `ACCEPT_GOOD_RETURNS` char(1) DEFAULT NULL,
  `RETURN_CREDIT_TYPE_ID` int(11) DEFAULT NULL,
  `COUNTRY_ID` int(11) DEFAULT NULL,
  `PROVINCES_ID` int(11) DEFAULT NULL,
  `AUDIT_ID` int(11) DEFAULT NULL,
  `CONTACT_PERSON_MIDDLE_NM` varchar(50) DEFAULT NULL,
  `CONTACT_PERSON_LAST_NM` varchar(50) DEFAULT NULL,
  `SUPPLIER_ALSO_MANUFACTURER` char(1) CHARACTER SET latin1 COLLATE latin1_swedish_ci DEFAULT 'N',
  `SUPPLIES_MEDICAL_NON_MEDICAL_BOTH` char(1) CHARACTER SET latin1 COLLATE latin1_swedish_ci DEFAULT 'B',
  PRIMARY KEY (`SUPPLIER_ID`),
  KEY `FK_SUPPLIER_RETURN_CREDIT_TYPE` (`RETURN_CREDIT_TYPE_ID`),
  KEY `FK_SUPPLIER_COUNTRY` (`COUNTRY_ID`),
  KEY `FK_SUPPLIER_PROVINCES_LOOKUP` (`PROVINCES_ID`),
  CONSTRAINT `FK_SUPPLIER_COUNTRY_LOOKUP` FOREIGN KEY (`COUNTRY_ID`) REFERENCES `country_lookup` (`COUNTRY_ID`) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT `FK_SUPPLIER_PROVINCES_LOOKUP` FOREIGN KEY (`PROVINCES_ID`) REFERENCES `provinces_lookup` (`PROVINCES_ID`) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT `FK_SUPPLIER_RETURN_CREDIT_TYPE` FOREIGN KEY (`RETURN_CREDIT_TYPE_ID`) REFERENCES `return_credit_type` (`RETURN_CREDIT_TYPE_ID`) ON DELETE RESTRICT ON UPDATE RESTRICT
) ;




DROP TABLE IF EXISTS `supplier_contract`;

CREATE TABLE `supplier_contract` (
  `SUPPLIER_CONTRACT_ID` int(11) NOT NULL AUTO_INCREMENT,
  `SUPPLIER_ID` int(11) NOT NULL,
  `CONTRACT_NO` varchar(20) NOT NULL,
  `CONTRACT_DT` date NOT NULL,
  `CONTRACT_EXPIRY_DT` date NOT NULL,
  `CONTRACT_VALUE` double DEFAULT NULL,
  `PAYMENT_TIME` int(11) NOT NULL,
  `DELIVERY_TIME` int(11) DEFAULT NULL,
  `CLASSIFICATION` varchar(100) DEFAULT NULL,
  `CREATION_TS` timestamp NULL DEFAULT NULL,
  `CREATION_USER_ID` varchar(50) DEFAULT NULL,
  `LAST_UPDATE_TS` timestamp NULL DEFAULT NULL,
  `LAST_UPDATE_USER_ID` varchar(50) DEFAULT NULL,
  `ACTIVE_S` char(1) CHARACTER SET latin1 COLLATE latin1_swedish_ci DEFAULT NULL,
  `AUDIT_ID` int(11) DEFAULT NULL,
  `REMARKS` varchar(500) DEFAULT NULL,
  `CONTRACT_DOCUMENT` blob,
  `QUOTATION_ID` int(11) DEFAULT NULL,
  PRIMARY KEY (`SUPPLIER_CONTRACT_ID`),
  KEY `FK_SUPPLIER_CONTRACT_SUPPLIER` (`SUPPLIER_ID`),
  KEY `FK_SUPPLIER_CONTRACT_QUOTATION` (`QUOTATION_ID`),
  CONSTRAINT `FK_SUPPLIER_CONTRACT_SUPPLIER` FOREIGN KEY (`SUPPLIER_ID`) REFERENCES `supplier` (`SUPPLIER_ID`) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT `FK_SUPPLIER_CONTRACT_QUOTATION` FOREIGN KEY (`QUOTATION_ID`) REFERENCES `quotation` (`QUOTATION_ID`) ON DELETE RESTRICT ON UPDATE RESTRICT
) ;





DROP TABLE IF EXISTS `supplier_contract_items`;

CREATE TABLE `supplier_contract_items` (
  `SUPPLIER_CONTRACT_ITEM_ID` int(11) NOT NULL AUTO_INCREMENT,
  `SUPPLIER_ID` int(11) DEFAULT NULL,
  `SUPPLIER_CONTRACT_ID` int(11) DEFAULT NULL,
  `ITEM_ID` int(11) DEFAULT NULL,
  `UNIT_PURCHASE_PRICE` double DEFAULT NULL,
  `ACTIVE_S` char(1) CHARACTER SET latin1 COLLATE latin1_swedish_ci DEFAULT NULL,
  `CREATION_TS` timestamp NULL DEFAULT NULL,
  `CREATION_USER_ID` varchar(50) DEFAULT NULL,
  `LAST_UPDATE_TS` timestamp NULL DEFAULT NULL,
  `LAST_UPDATE_USER_ID` varchar(50) DEFAULT NULL,
  `AUDIT_ID` int(11) DEFAULT NULL,
  `CURRENT_SUPPLIER` char(1) CHARACTER SET latin1 COLLATE latin1_swedish_ci DEFAULT 'Y',
  `UNIT_TAX` float DEFAULT NULL,
  `QTY_BONUS` int(11) DEFAULT NULL,
  `DISCOUNT` float DEFAULT NULL,
  `DISCOUNT_PERCENTAGE` float DEFAULT NULL,
  `APPROVED_SUPPLIER` char(1) CHARACTER SET latin1 COLLATE latin1_swedish_ci DEFAULT 'Y',
  PRIMARY KEY (`SUPPLIER_CONTRACT_ITEM_ID`),
  KEY `FK_SUPPLIER_CONTRACT_ITEM_CONTRACT` (`SUPPLIER_CONTRACT_ID`),
  KEY `FK_SUPPLIER_CONTRACT_ITEM_SUPPLIER` (`SUPPLIER_ID`),
  KEY `FK_SUPPLIER_CONTRACT_ITEM_ITEMS` (`ITEM_ID`),
  CONSTRAINT `FK_SUPPLIER_CONTRACT_ITEM_CONTRACT` FOREIGN KEY (`SUPPLIER_CONTRACT_ID`) REFERENCES `supplier_contract` (`SUPPLIER_CONTRACT_ID`) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT `FK_SUPPLIER_CONTRACT_ITEM_SUPPLIER` FOREIGN KEY (`SUPPLIER_ID`) REFERENCES `supplier` (`SUPPLIER_ID`) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT `FK_SUPPLIER_CONTRACT_ITEM_ITEMS` FOREIGN KEY (`ITEM_ID`) REFERENCES `items` (`ITEM_ID`) ON DELETE RESTRICT ON UPDATE RESTRICT
);


DROP TABLE IF EXISTS `employee`;

CREATE TABLE `employee` (
  `EMPLOYEE_ID` int(11) NOT NULL AUTO_INCREMENT,
  `PHONE_NBR` varchar(20) DEFAULT NULL,
  `TITLE` varchar(5) DEFAULT NULL,
  `FIRST_NM` varchar(50) NOT NULL,
  `MIDDLE_NM` varchar(50) DEFAULT NULL,
  `LAST_NM` varchar(50) NOT NULL,
  `GENDER_CD` char(1) DEFAULT NULL,
  `DOB_DT` date DEFAULT NULL,
  `DATE_OF_JOINING` date DEFAULT NULL,
  `EMAIL_ID` varchar(50) DEFAULT NULL,
  `DESIGNATION_NM` varchar(250) DEFAULT NULL,
  `BIOGRAPHY_DESC` varchar(5000) DEFAULT NULL,
  `ADDRESS_LINE1` varchar(250) DEFAULT NULL,
  `ADDRESS_LINE2` varchar(250) DEFAULT NULL,
  `CITY_NM` varchar(50) DEFAULT NULL,
  `BLOOD_GROUP` varchar(20) DEFAULT NULL,
  `ARE_YOU_WORK_ON_SHIFTS` char(2) DEFAULT NULL,
  `POSTAL_CD` varchar(20) DEFAULT NULL,
  `CREATION_TS` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `CREATION_USER_ID` varchar(50) NOT NULL,
  `LAST_UPDATE_TS` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00',
  `LAST_UPDATE_USER_ID` varchar(50) DEFAULT NULL,
  `PROFILE_IMAGE` blob,
  `AUDIT_ID` int(11) DEFAULT NULL,
  `EMPLOYEE_TYPE_LOOKUP_ID` int(11) DEFAULT NULL,
  `PHARMACY_ID` int(11) DEFAULT NULL,
  `SALARY` double DEFAULT NULL,
  `EMPLOYEE_TYPE_FULL_PART_TIME` varchar(50) DEFAULT NULL,
  `COUNTRY_ID` int(11) DEFAULT NULL,
  `PROVINCES_ID` int(11) DEFAULT NULL,
  `ACTIVE_S` char(1) CHARACTER SET latin1 COLLATE latin1_swedish_ci DEFAULT 'Y',
  `EMPLOYEE_CD` varchar(20) DEFAULT NULL,
  `KRA_PIN` varchar(20) DEFAULT NULL,
  `IDENTIFICATION_DOCUMENT` blob,
  `NHIF_NO` varchar(20) DEFAULT NULL,
  `POLICE_GOOD_CONDUCT_CERTIFICATE` blob,
  `RESUME` blob,
  `SIGNED_CONTRACT` blob,
  `LANDLINE_NUMBER` varchar(20) DEFAULT NULL,
  `POST_BOX` varchar(20) DEFAULT NULL,
  `IDENTIFICATION_NO` varchar(20) DEFAULT NULL,
  `NSSF_NO` varchar(20) DEFAULT NULL,
  PRIMARY KEY (`EMPLOYEE_ID`),
  KEY `FK_EMPLOYEE_COUNTRY_LOOKUP` (`COUNTRY_ID`),
  KEY `FK_EMPLOYEE_EMPLOYEE_TYPE_LOOKUP` (`EMPLOYEE_TYPE_LOOKUP_ID`),
  KEY `FK_EMPLOYEE_PROVINCES_LOOKUP` (`PROVINCES_ID`),
  CONSTRAINT `FK_EMPLOYEE_COUNTRY_LOOKUP` FOREIGN KEY (`COUNTRY_ID`) REFERENCES `country_lookup` (`COUNTRY_ID`) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT `FK_EMPLOYEE_EMPLOYEE_TYPE_LOOKUP` FOREIGN KEY (`EMPLOYEE_TYPE_LOOKUP_ID`) REFERENCES `employee_type_lookup` (`EMPLOYEE_TYPE_LOOKUP_ID`) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT `FK_EMPLOYEE_PROVINCES_LOOKUP` FOREIGN KEY (`PROVINCES_ID`) REFERENCES `provinces_lookup` (`PROVINCES_ID`) ON DELETE RESTRICT ON UPDATE RESTRICT
) ;



DROP TABLE IF EXISTS `employee_access`;

CREATE TABLE `employee_access` (
  `EMPLOYEE_ACCESS_ID` int(11) NOT NULL AUTO_INCREMENT,
  `EMPLOYEE_ID` int(11) NOT NULL,
  `PHARMA_ACCESS_ID` int(11) NOT NULL,
  `CREATION_TS` timestamp NULL DEFAULT NULL,
  `CREATION_USER_ID` varchar(50) DEFAULT NULL,
  `LAST_UPDATE_TS` timestamp NULL DEFAULT NULL,
  `LAST_UPDATE_USER_ID` varchar(50) DEFAULT NULL,
  `ACTIVE_S` char(1) CHARACTER SET latin1 COLLATE latin1_swedish_ci DEFAULT 'Y',
  PRIMARY KEY (`EMPLOYEE_ACCESS_ID`),
  KEY `FK_EMPLOYEE_ACCESS_EMPLOYEE_ID` (`EMPLOYEE_ID`),
  KEY `FK_EMPLOYEE_ACCESS_PHARMA_ACCESS` (`PHARMA_ACCESS_ID`),
  CONSTRAINT `FK_EMPLOYEE_ACCESS_EMPLOYEE_ID` FOREIGN KEY (`EMPLOYEE_ID`) REFERENCES `employee` (`EMPLOYEE_ID`) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT `FK_EMPLOYEE_ACCESS_PHARMA_ACCESS` FOREIGN KEY (`PHARMA_ACCESS_ID`) REFERENCES `pharma_access` (`PHARMA_ACCESS_ID`) ON DELETE RESTRICT ON UPDATE RESTRICT
) ;



DROP TABLE IF EXISTS `employee_credentials`;

CREATE TABLE `employee_credentials` (
  `EMPLOYEE_CREDENTIALS_ID` int(11) NOT NULL AUTO_INCREMENT,
  `EMPLOYEE_ID` int(11) NOT NULL,
  `USER_NM` varchar(50) NOT NULL,
  `CURRENT_PASSWORD` varchar(50) NOT NULL,
  `PREVIOUS_PASSWORD1` varchar(50) DEFAULT NULL,
  `PREVIOUS_PASSWORD2` varchar(50) DEFAULT NULL,
  `ACTIVE_S` char(1) CHARACTER SET latin1 COLLATE latin1_swedish_ci DEFAULT 'Y',
  `CREATION_TS` timestamp NULL DEFAULT NULL,
  `CREATION_USER_ID` varchar(50) DEFAULT NULL,
  `LAST_UPDATE_TS` timestamp NULL DEFAULT NULL,
  `LAST_UPDATE_USER_ID` varchar(50) DEFAULT NULL,
  `AUDIT_ID` int(11) DEFAULT NULL,
  `PASSWORD_STATUS` tinyint(4) DEFAULT '0',
  PRIMARY KEY (`EMPLOYEE_CREDENTIALS_ID`),
  KEY `FK_EMPLOYEE_CREDENTIALS_EMPLOYEE` (`EMPLOYEE_ID`),
  CONSTRAINT `FK_EMPLOYEE_CREDENTIALS_EMPLOYEE` FOREIGN KEY (`EMPLOYEE_ID`) REFERENCES `employee` (`EMPLOYEE_ID`) ON DELETE RESTRICT ON UPDATE RESTRICT
) ;



DROP TABLE IF EXISTS `employee_education`;

CREATE TABLE `employee_education` (
  `EMPLOYEE_EDUCATION_ID` int(11) NOT NULL AUTO_INCREMENT,
  `EMPLOYEE_ID` int(11) NOT NULL,
  `STUDIED_AT` varchar(250) DEFAULT NULL,
  `DEGREE` varchar(250) DEFAULT NULL,
  `GARDUATION_DATE` date DEFAULT NULL,
  `CREATION_TS` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `CREATION_USER_ID` varchar(50) NOT NULL,
  `LAST_UPDATE_TS` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00',
  `LAST_UPDATE_USER_ID` varchar(50) DEFAULT NULL,
  `AUDIT_ID` int(11) DEFAULT NULL,
  `CERTIFICATE` blob,
  PRIMARY KEY (`EMPLOYEE_EDUCATION_ID`),
  KEY `FK_EMPLOYEE_EDUCATION_PVDR` (`EMPLOYEE_ID`),
  CONSTRAINT `FK_EMPLOYEE_EDUCATION_EMPLOYEE` FOREIGN KEY (`EMPLOYEE_ID`) REFERENCES `employee` (`EMPLOYEE_ID`) ON DELETE RESTRICT ON UPDATE RESTRICT
) ;





CREATE TABLE `employee_honor` (
  `EMPLOYEE_HONOR_ID` int(11) NOT NULL AUTO_INCREMENT,
  `EMPLOYEE_ID` int(11) NOT NULL,
  `HONOR_NM` varchar(250) DEFAULT NULL,
  `HONOR_DESC` varchar(250) DEFAULT NULL,
  `RECEIVE_DT` date DEFAULT NULL,
  `CREATION_TS` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `CREATION_USER_ID` varchar(50) NOT NULL,
  `LAST_UPDATE_TS` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00',
  `LAST_UPDATE_USER_ID` varchar(50) DEFAULT NULL,
  `AUDIT_ID` int(11) DEFAULT NULL,
  PRIMARY KEY (`EMPLOYEE_HONOR_ID`),
  KEY `FK_EMPLOYEE_HONOR_PVDR` (`EMPLOYEE_ID`),
  CONSTRAINT `FK_EMPLOYEE_HONOR_EMPLOYEE` FOREIGN KEY (`EMPLOYEE_ID`) REFERENCES `employee` (`EMPLOYEE_ID`) ON DELETE RESTRICT ON UPDATE RESTRICT
) ;




DROP TABLE IF EXISTS `employee_images`;

CREATE TABLE `employee_images` (
  `EMPLOYEE_IMAGE_ID` int(11) NOT NULL AUTO_INCREMENT,
  `IMAGE_DESC` varchar(50) DEFAULT NULL,
  `IMAGE` blob,
  `EMPLOYEE_ID` int(11) DEFAULT NULL,
  PRIMARY KEY (`EMPLOYEE_IMAGE_ID`),
  KEY `FK_EMPLOYEE_ID_idx` (`EMPLOYEE_ID`),
  CONSTRAINT `FK_EMPLOYEE_ID` FOREIGN KEY (`EMPLOYEE_ID`) REFERENCES `employee` (`EMPLOYEE_ID`)
) ;





DROP TABLE IF EXISTS `employee_interest`;

CREATE TABLE `employee_interest` (
  `EMPLOYEE_INTEREST_ID` int(11) NOT NULL AUTO_INCREMENT,
  `EMPLOYEE_ID` int(11) NOT NULL,
  `AREA_OF_INTEREST_DESC` varchar(250) DEFAULT NULL,
  `CREATION_TS` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `CREATION_USER_ID` varchar(50) NOT NULL,
  `LAST_UPDATE_TS` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00',
  `LAST_UPDATE_USER_ID` varchar(50) DEFAULT NULL,
  `INTRESTED_AT` varchar(250) DEFAULT NULL,
  `AUDIT_ID` int(11) DEFAULT NULL,
  PRIMARY KEY (`EMPLOYEE_INTEREST_ID`),
  KEY `FK_EMPLOYEE_INTEREST_PVDR` (`EMPLOYEE_ID`),
  CONSTRAINT `FK_EMPLOYEE_INTREST_EMPLOYEE` FOREIGN KEY (`EMPLOYEE_ID`) REFERENCES `employee` (`EMPLOYEE_ID`) ON DELETE RESTRICT ON UPDATE RESTRICT
) ;


DROP TABLE IF EXISTS `employee_pharmacy_role`;

CREATE TABLE `employee_pharmacy_role` (
  `EMPLOYEE_PHARMACY_ROLE_ID` int(11) NOT NULL AUTO_INCREMENT,
  `EMPLOYEE_ID` int(11) NOT NULL,
  `PHARMACY_BRANCH_ID` int(11) NOT NULL,
  `ROLE_ID` int(11) NOT NULL,
  `CREATION_TS` timestamp NULL DEFAULT NULL,
  `CREATION_USER_ID` varchar(50) DEFAULT NULL,
  `LAST_UPDATE_TS` timestamp NULL DEFAULT NULL,
  `LAST_UPDATE_USER_ID` varchar(50) DEFAULT NULL,
  `AUDIT_ID` int(11) DEFAULT NULL,
  PRIMARY KEY (`EMPLOYEE_PHARMACY_ROLE_ID`),
  KEY `FK_EMPLOYEE_PHARMACY_ROLE_EMPLOYEE` (`EMPLOYEE_ID`),
  KEY `FK_EMPLOYEE_PHARMACY_ROLE_PHARMACY_BRANCH_idx` (`PHARMACY_BRANCH_ID`),
  KEY `FK_EMPLOYEE_PHARMACY_ROLE_ROLES` (`ROLE_ID`),
  CONSTRAINT `FK_EMPLOYEE_PHARMACY_ROLE_EMPLOYEE` FOREIGN KEY (`EMPLOYEE_ID`) REFERENCES `employee` (`EMPLOYEE_ID`) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT `FK_EMPLOYEE_PHARMACY_ROLE_PHARMACY_BRANCH` FOREIGN KEY (`PHARMACY_BRANCH_ID`) REFERENCES `pharmacy` (`PHARMACY_ID`) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT `FK_EMPLOYEE_PHARMACY_ROLE_ROLES` FOREIGN KEY (`ROLE_ID`) REFERENCES `pharmacy_roles` (`ROLE_ID`) ON DELETE RESTRICT ON UPDATE RESTRICT
) ;



DROP TABLE IF EXISTS `employee_prof_membership`;

CREATE TABLE `employee_prof_membership` (
  `EMPLOYEE_PROF_MEMBERSHIP_ID` int(11) NOT NULL AUTO_INCREMENT,
  `EMPLOYEE_ID` int(11) NOT NULL,
  `MEMBERSHIP_NM` varchar(250) DEFAULT NULL,
  `START_DT` date DEFAULT NULL,
  `END_DT` date DEFAULT NULL,
  `CREATION_TS` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `CREATION_USER_ID` varchar(50) NOT NULL,
  `LAST_UPDATE_TS` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00',
  `LAST_UPDATE_USER_ID` varchar(50) DEFAULT NULL,
  `AUDIT_ID` int(11) DEFAULT NULL,
  PRIMARY KEY (`EMPLOYEE_PROF_MEMBERSHIP_ID`),
  KEY `FK_EMPLOYEE_PROF_MEMBERSHIP_PVDR` (`EMPLOYEE_ID`),
  CONSTRAINT `FK_EMPLOYEE_PROF_MEMBERSHIP_EMPLOYEE` FOREIGN KEY (`EMPLOYEE_ID`) REFERENCES `employee` (`EMPLOYEE_ID`) ON DELETE RESTRICT ON UPDATE RESTRICT
) ;



DROP TABLE IF EXISTS `employee_publication`;

CREATE TABLE `employee_publication` (
  `EMPLOYEE_PUBLICATION_ID` int(11) NOT NULL AUTO_INCREMENT,
  `EMPLOYEE_ID` int(11) NOT NULL,
  `PUBLICATION_NM` varchar(250) DEFAULT NULL,
  `PUBLICATION_DESC` varchar(250) DEFAULT NULL,
  `PUBLISH_DT` date DEFAULT NULL,
  `CREATION_TS` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `CREATION_USER_ID` varchar(50) NOT NULL,
  `LAST_UPDATE_TS` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00',
  `LAST_UPDATE_USER_ID` varchar(50) DEFAULT NULL,
  `AUDIT_ID` int(11) DEFAULT NULL,
  PRIMARY KEY (`EMPLOYEE_PUBLICATION_ID`),
  KEY `FK_EMPLOYEE_PUBLICATION_PVDR` (`EMPLOYEE_ID`),
  CONSTRAINT `FK_EMPLOYEE_PUBLICATION_EMPLOYEE` FOREIGN KEY (`EMPLOYEE_ID`) REFERENCES `employee` (`EMPLOYEE_ID`) ON DELETE RESTRICT ON UPDATE RESTRICT
);



DROP TABLE IF EXISTS `employee_salary`;

CREATE TABLE `employee_salary` (
  `EMPLOYEE_SALARY_ID` int(11) NOT NULL AUTO_INCREMENT,
  `AUDIT_ID` int(11) DEFAULT NULL,
  `EMPLOYEE_ID` int(11) DEFAULT NULL,
  `CREATION_TS` timestamp NULL DEFAULT NULL,
  `CREATION_USER_ID` varchar(50) DEFAULT NULL,
  `LAST_UPDATE_TS` timestamp NULL DEFAULT NULL,
  `LAST_UPDATE_USER_ID` varchar(50) DEFAULT NULL,
  `SALARY_DT` date DEFAULT NULL,
  `BASIC` double DEFAULT NULL,
  `HRA` double DEFAULT NULL,
  `DA` double DEFAULT NULL,
  `MEDICAL` double DEFAULT NULL,
  `P_TAX` double DEFAULT NULL,
  `PF_EMPLOYEE` double DEFAULT NULL,
  `PF_EMPLOYER` double DEFAULT NULL,
  `TDS` double DEFAULT NULL,
  `ESI` double DEFAULT NULL,
  `GROSS_SALARY` double DEFAULT NULL,
  PRIMARY KEY (`EMPLOYEE_SALARY_ID`),
  KEY `FK_EMPLOYEE_SALARY_EMPLOYEE` (`EMPLOYEE_ID`),
  CONSTRAINT `FK_EMPLOYEE_SALARY_EMPLOYEE` FOREIGN KEY (`EMPLOYEE_ID`) REFERENCES `employee` (`EMPLOYEE_ID`) ON DELETE RESTRICT ON UPDATE RESTRICT
) ;



DROP TABLE IF EXISTS `employee_type_lookup`;

CREATE TABLE `employee_type_lookup` (
  `EMPLOYEE_TYPE_LOOKUP_ID` int(11) NOT NULL AUTO_INCREMENT,
  `EMPLOYEE_TYPE_CD` char(2) NOT NULL,
  `EMPLOYEE_TYPE_DESC` varchar(250) DEFAULT NULL,
  `CREATION_TS` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `CREATION_USER_ID` varchar(50) NOT NULL,
  `LAST_UPDATE_TS` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00',
  `LAST_UPDATE_USER_ID` varchar(50) DEFAULT NULL,
  `AUDIT_ID` int(11) DEFAULT NULL,
  PRIMARY KEY (`EMPLOYEE_TYPE_LOOKUP_ID`)
) ;


DROP TABLE IF EXISTS `employment_history`;

CREATE TABLE `employment_history` (
  `EMPLOYMENT_HISTORY_ID` int(11) NOT NULL AUTO_INCREMENT,
  `COMPANY_NAME` varchar(100) NOT NULL,
  `START_DT` date DEFAULT NULL,
  `END_DT` date DEFAULT NULL,
  `COMPANY_ADDRESS` varchar(250) DEFAULT NULL,
  `REPORTING_PERSON_DETAILS` varchar(50) DEFAULT NULL,
  `MANAGER_NM` varchar(50) DEFAULT NULL,
  `MANAGER_PHONE_NBR` varchar(20) DEFAULT NULL,
  `MANAGER_EMAIL_ID` varchar(50) DEFAULT NULL,
  `DESIGNATION` varchar(50) DEFAULT NULL,
  `EMPLOYMENT_TYPE` varchar(50) DEFAULT NULL,
  `REFERENCE1` varchar(50) DEFAULT NULL,
  `REFERENCE2` varchar(50) DEFAULT NULL,
  `CREATION_TS` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `CREATION_USER_ID` varchar(50) NOT NULL,
  `LAST_UPDATE_TS` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00',
  `LAST_UPDATE_USER_ID` varchar(50) DEFAULT NULL,
  `AUDIT_ID` int(11) DEFAULT NULL,
  `EMPLOYEE_ID` int(11) DEFAULT NULL,
  PRIMARY KEY (`EMPLOYMENT_HISTORY_ID`),
  KEY `FK_EMPLOYMENT_HISTORY_EMPLOYEE` (`EMPLOYEE_ID`),
  CONSTRAINT `FK_EMPLOYMENT_HISTORY_EMPLOYEE` FOREIGN KEY (`EMPLOYEE_ID`) REFERENCES `employee` (`EMPLOYEE_ID`) ON DELETE RESTRICT ON UPDATE RESTRICT
) ;


DROP TABLE IF EXISTS `expiry_profile`;

CREATE TABLE `expiry_profile` (
  `EXPIRY_PROFILE_ID` int(11) NOT NULL AUTO_INCREMENT,
  `EXPIRY_CD` varchar(20) DEFAULT NULL,
  `EXPIRY_DAYS` int(11) DEFAULT NULL,
  `CREATION_TS` timestamp NULL DEFAULT NULL,
  `CREATION_USER_ID` varchar(50) DEFAULT NULL,
  `LAST_UPDATE_TS` timestamp NULL DEFAULT NULL,
  `LAST_UPDATE_USER_ID` varchar(50) DEFAULT NULL,
  `AUDIT_ID` int(11) DEFAULT NULL,
  PRIMARY KEY (`EXPIRY_PROFILE_ID`)
) ;




CREATE TABLE `formulation_instructions` (
  `FORMULATION_INSTRUCTION_ID` int(11) NOT NULL AUTO_INCREMENT,
  `FORMULATION_NAME` varchar(100) NOT NULL,
  `INSTRUCTIONS` varchar(255) NOT NULL,
  `ITEM_ID` int(11) NULL,
  `PHARMACY_ID` int(11) DEFAULT NULL,
  `TIMES_IN_A_DAY` int(11) DEFAULT NULL,
  `MORNING` char(1)CHARACTER SET latin1 COLLATE latin1_swedish_ci DEFAULT 'Y',
  `AFTER_NOON` char(1) CHARACTER SET latin1 COLLATE latin1_swedish_ci DEFAULT 'Y',
  `EVENING` char(1)  CHARACTER SET latin1 COLLATE latin1_swedish_ci DEFAULT 'Y',
  `BEFORE_BED` char(1) CHARACTER SET latin1 COLLATE latin1_swedish_ci DEFAULT 'Y',
  `TIMINGS` int(11) DEFAULT NULL,
  `AFTER_MEAL` char(1)CHARACTER SET latin1 COLLATE latin1_swedish_ci DEFAULT 'Y',
  `BEFORE_MEAL` char(1)  CHARACTER SET latin1 COLLATE latin1_swedish_ci DEFAULT 'Y',
  `ANY_TIME` char(1) CHARACTER SET latin1 COLLATE latin1_swedish_ci DEFAULT 'Y',
  `CREATION_TS` timestamp NULL DEFAULT NULL,
  `CREATION_USER_ID` varchar(50) DEFAULT NULL,
  `LAST_UPDATE_TS` timestamp NULL DEFAULT NULL,
  `LAST_UPDATE_USER_ID` varchar(50) DEFAULT NULL,
  `AUDIT_ID` int(11) DEFAULT NULL,
  `ACTIVE_S` char(1) CHARACTER SET latin1 COLLATE latin1_swedish_ci DEFAULT 'Y',  
   PRIMARY KEY (`FORMULATION_INSTRUCTION_ID`),
     KEY `FK_FORMULATION_ITEM` (`ITEM_ID`),
	 KEY `FK_FORMULATION_PHARMACY` (`PHARMACY_ID`),
    CONSTRAINT `FK_FORMULATION_ITEM` FOREIGN KEY (`ITEM_ID`) REFERENCES `items` (`ITEM_ID`) ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT `FK_FORMULATION_PHARMACY` FOREIGN KEY (`PHARMACY_ID`) REFERENCES `pharmacy` (`PHARMACY_ID`) ON DELETE RESTRICT ON UPDATE RESTRICT
);



DROP TABLE IF EXISTS `hospital`;

CREATE TABLE `hospital` (
  `HOSPITAL_ID` int(11) NOT NULL AUTO_INCREMENT,
  `NAME` varchar(100) DEFAULT NULL,
  `LICENSE` varchar(100) DEFAULT NULL,
  `PHONE_NBR` varchar(20) DEFAULT NULL,
  `EMAIL_ID` varchar(50) DEFAULT NULL,
  `CREATION_TS` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `CREATION_USER_ID` varchar(50) DEFAULT NULL,
  `LAST_UPDATE_TS` timestamp NULL DEFAULT '0000-00-00 00:00:00',
  `LAST_UPDATE_USER_ID` varchar(50) DEFAULT NULL,
  `FAX` varchar(20) DEFAULT NULL,
  `ACTIVE_S` char(1) CHARACTER SET latin1 COLLATE latin1_swedish_ci DEFAULT 'Y',
  `ADDRESS_LINE1` varchar(250) DEFAULT NULL,
  `ADDRESS_LINE2` varchar(250) DEFAULT NULL,
  `CITY_NM` varchar(50) DEFAULT NULL,
  `ZIP_CD` varchar(10) DEFAULT NULL,
  `WEBSITE` varchar(50) DEFAULT NULL,
  `HELPLINE` varchar(20) DEFAULT NULL,
  `CONTACT_NBR` varchar(20) DEFAULT NULL,
  `AUDIT_ID` int(11) DEFAULT NULL,
  `COUNTRY_ID` int(11) DEFAULT NULL,
  `PROVINCES_ID` int(11) DEFAULT NULL,
  PRIMARY KEY (`HOSPITAL_ID`),
  KEY `FK_HOSPITAL_COUNTRY_LOOKUP` (`COUNTRY_ID`),
  KEY `FK_HOSPITAL_PROVINCES_LOOKUP` (`PROVINCES_ID`),
  CONSTRAINT `FK_HOSPITAL_COUNTRY_LOOKUP` FOREIGN KEY (`COUNTRY_ID`) REFERENCES `country_lookup` (`COUNTRY_ID`) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT `FK_HOSPITAL_PROVINCES_LOOKUP` FOREIGN KEY (`PROVINCES_ID`) REFERENCES `provinces_lookup` (`PROVINCES_ID`) ON DELETE RESTRICT ON UPDATE RESTRICT
) ;



DROP TABLE IF EXISTS `indent`;

CREATE TABLE `indent` (
  `INDENT_ID` int(11) NOT NULL AUTO_INCREMENT,
  `INDENT_NO` varchar(20) NOT NULL,
  `INDENT_DT` date NOT NULL,
  `REQUEST_DT` date DEFAULT NULL,
  `STATUS` char(1) CHARACTER SET latin1 COLLATE latin1_swedish_ci DEFAULT NULL,
  `REMARKS` varchar(200) DEFAULT NULL,
  `CREATED_BY` int(11) DEFAULT NULL,
  `EMERGENCY` char(1) CHARACTER SET latin1 COLLATE latin1_swedish_ci DEFAULT NULL,
  `CREATION_TS` timestamp NULL DEFAULT NULL,
  `CREATION_USER_ID` varchar(50) DEFAULT NULL,
  `LAST_UPDATE_TS` timestamp NULL DEFAULT NULL,
  `LAST_UPDATE_USER_ID` varchar(50) DEFAULT NULL,
  `MODIFIED_BY` int(11) DEFAULT NULL,
  `MODIFIED_DT` date DEFAULT NULL,
  `APPROVED_BY` int(11) DEFAULT NULL,
  `APPROVED_DT` date DEFAULT NULL,
  `CANCELLED_BY` int(11) DEFAULT NULL,
  `CANCELLED_DT` date DEFAULT NULL,
  `RFQ` varchar(20) DEFAULT NULL,
  `REQ` varchar(20) DEFAULT NULL,
  `SYSTEM_NM` varchar(50) DEFAULT NULL,
  `AUDIT_ID` int(11) DEFAULT NULL,
  `REJECTED_REASON` varchar(200) DEFAULT NULL,
  `INDENT_STATUS_ID` int(11) DEFAULT NULL,
  PRIMARY KEY (`INDENT_ID`),
  KEY `FK_INDENT_STATUS` (`INDENT_STATUS_ID`),
  CONSTRAINT `FK_INDENT_STATUS` FOREIGN KEY (`INDENT_STATUS_ID`) REFERENCES `indent_status` (`INDENT_STATUS_ID`) ON DELETE RESTRICT ON UPDATE RESTRICT
) ;


DROP TABLE IF EXISTS `indent_items`;

CREATE TABLE `indent_items` (
  `INDENT_ITEM_ID` int(11) NOT NULL AUTO_INCREMENT,
  `INDENT_ID` int(11) NOT NULL,
  `ITEM_ID` int(11) NOT NULL,
  `QUANTITY` int(11) NOT NULL,
  `REMARKS` varchar(200) DEFAULT NULL,
  `CREATION_TS` timestamp NULL DEFAULT NULL,
  `CREATION_USER_ID` varchar(50) DEFAULT NULL,
  `LAST_UPDATE_TS` timestamp NULL DEFAULT NULL,
  `LAST_UPDATE_USER_ID` varchar(50) DEFAULT NULL,
  `STATUS` char(1) CHARACTER SET latin1 COLLATE latin1_swedish_ci DEFAULT NULL,
  `AUDIT_ID` int(11) DEFAULT NULL,
  PRIMARY KEY (`INDENT_ITEM_ID`),
  KEY `FK_INDENT_ITEM_INDENT` (`INDENT_ID`),
  KEY `FK_INDENT_ITEM_ITEM` (`ITEM_ID`),
  CONSTRAINT `FK_INDENT_ITEM_INDENT` FOREIGN KEY (`INDENT_ID`) REFERENCES `indent` (`INDENT_ID`) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT `FK_INDENT_ITEM_ITEM` FOREIGN KEY (`ITEM_ID`) REFERENCES `items` (`ITEM_ID`) ON DELETE RESTRICT ON UPDATE RESTRICT
);



DROP TABLE IF EXISTS `indent_status`;

CREATE TABLE `indent_status` (
  `INDENT_STATUS_ID` int(11) NOT NULL AUTO_INCREMENT,
  `STATUS` varchar(20) DEFAULT NULL,
  PRIMARY KEY (`INDENT_STATUS_ID`)
) ;



DROP TABLE IF EXISTS `insurance`;

CREATE TABLE `insurance` (
  `INSURANCE_POLICY_ID` int(11) NOT NULL AUTO_INCREMENT,
  `POLICY_CD` varchar(100) NOT NULL,
  `POLICY_DESC` varchar(200) NOT NULL,
  `COMPANY_NM` varchar(100) NOT NULL,
  `POLICY_START` date NOT NULL,
  `POLICY_END` date NOT NULL,
  `POLICY_DURATION_IN_MONTHS` int(11) DEFAULT NULL,
  `POLICY_AMOUNT_LIMIT` float NOT NULL,
  `MEDICINES_NOT_COVERED` varchar(1000) DEFAULT NULL,
  `TERMS_AND_CONDITIONS` varchar(250) DEFAULT NULL,
  `TERMS_AND_CONDITIONS_FILE` blob,
  `AUDIT_ID` int(11) DEFAULT NULL,
  `CREATION_TS` timestamp NULL DEFAULT NULL,
  `CREATION_USER_ID` varchar(50) DEFAULT NULL,
  `LAST_UPDATE_TS` timestamp NULL DEFAULT NULL,
  `LAST_UPDATE_USER_ID` varchar(50) DEFAULT NULL,
  `ACTIVE_S` char(1) CHARACTER SET latin1 COLLATE latin1_swedish_ci DEFAULT 'Y',
  `CONTACT_FIRST_NM` varchar(50) DEFAULT NULL,
  `CONTACT_LAST_NM` varchar(50) DEFAULT NULL,
  `CONTACT_PERSON_EMAIL_ID` varchar(50) DEFAULT NULL,
  `CONTACT_PERSON_PHONE_NBR` varchar(20) DEFAULT NULL,
  `ADDRESS_LINE1` varchar(250) DEFAULT NULL,
  `ADDRESS_LINE2` varchar(250) DEFAULT NULL,
  `CITY_NM` varchar(50) DEFAULT NULL,
  `ZIP_CD` varchar(10) DEFAULT NULL,
  `COUNTRY_ID` int(11) DEFAULT NULL,
  `PROVINCES_ID` int(11) DEFAULT NULL,
  `EMAIL_ID` varchar(50) DEFAULT NULL,
  `CONTACT_NBR` varchar(20) DEFAULT NULL,
  `PHARMACY_ID` int(11) DEFAULT NULL,
  PRIMARY KEY (`INSURANCE_POLICY_ID`),
  KEY `FK_INSURANCE_COUNTRY_LOOKUP` (`COUNTRY_ID`),
  KEY `FK_INSURANCE_PROVINCES_LOOKUP` (`PROVINCES_ID`),
  KEY `FK_INSURANCE_PHARMACY` (`PHARMACY_ID`),
  CONSTRAINT `FK_INSURANCE_COUNTRY_LOOKUP` FOREIGN KEY (`COUNTRY_ID`) REFERENCES `country_lookup` (`COUNTRY_ID`) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT `FK_INSURANCE_PHARMACY` FOREIGN KEY (`PHARMACY_ID`) REFERENCES `pharmacy` (`PHARMACY_ID`) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT `FK_INSURANCE_PROVINCES_LOOKUP` FOREIGN KEY (`PROVINCES_ID`) REFERENCES `provinces_lookup` (`PROVINCES_ID`) ON DELETE RESTRICT ON UPDATE RESTRICT
);



DROP TABLE IF EXISTS `invoice`;

CREATE TABLE `invoice` (
  `INVOICE_ID` int(11) NOT NULL AUTO_INCREMENT,
  `INVOICE_NO` varchar(20) DEFAULT NULL,
  `SUPPLIER_ID` int(11) DEFAULT NULL,
  `INVOICE_DT` date DEFAULT NULL,
  `REMARKS` varchar(200) DEFAULT NULL,
  `CREATED_BY` int(11) DEFAULT NULL,
  `CREATION_TS` timestamp NULL DEFAULT NULL,
  `CREATION_USER_ID` varchar(50) DEFAULT NULL,
  `LAST_UPDATE_TS` timestamp NULL DEFAULT NULL,
  `LAST_UPDATE_USER_ID` varchar(50) DEFAULT NULL,
  `APPROVED_BY` int(11) DEFAULT NULL,
  `APPROVED_DT` date DEFAULT NULL,
  `MODIFIED_BY` int(11) DEFAULT NULL,
  `MODIFIED_DT` date DEFAULT NULL,
  `PHARMACY_ID` int(11) DEFAULT NULL,
  `PAYMENT_TYPE_ID` int(11) DEFAULT NULL,
  `CREDIT_DAYS` int(11) DEFAULT NULL,
  `INVOICE_STATUS_ID` int(11) DEFAULT NULL,
  `INVOICE` blob,
  `INVOICE_AMOUNT` double DEFAULT NULL,
  `AUDIT_ID` int(11) DEFAULT NULL,
  `INVOICE_ACTUAL_AMOUNT` double DEFAULT NULL,
  `MEDICAL_OR_NON_MEDICAL` char(1) CHARACTER SET latin1 COLLATE latin1_swedish_ci DEFAULT NULL,
  `PAID_AMOUNT` double DEFAULT NULL,
  `BALANCE` double DEFAULT NULL,
  `TAX_AMOUNT` double DEFAULT NULL,
  `DISCOUNT_PERCENTAGE` double DEFAULT NULL,
  `DISCOUNT` double DEFAULT NULL,
  `ADVANCE` double DEFAULT NULL,
  `HANDLING_CHARGES` double DEFAULT NULL,
  `TAX_PERCENTAGE` double DEFAULT NULL,
  `PURCHASE_TAX_AMOUNT` double DEFAULT NULL,
  `GRN_NO` varchar(20) DEFAULT NULL,
  `ROUND_OFF` double DEFAULT NULL,
  `PARCEL_NO` varchar(50) DEFAULT NULL,
  `BROUGHT_BY` varchar(50) DEFAULT NULL,
  `TOTAL_REJECTS` int(11) DEFAULT NULL,
  PRIMARY KEY (`INVOICE_ID`),
  KEY `FK_PURCHASE_INVOICE_APPROVED_BY` (`APPROVED_BY`),
  KEY `FK_PURCHASE_INVOICE_CREATED_BY` (`CREATED_BY`),
  KEY `FK_PURCHASE_INVOICE_SUPPLIER` (`SUPPLIER_ID`),
  KEY `FK_PURCHASE_INVOICE_MODIFIED_BY` (`MODIFIED_BY`),
  KEY `FK_PURCHASE_INVOICE_PAYMENT_TYPE` (`PAYMENT_TYPE_ID`),
  KEY `FK_PURCHASE_INVOICE_PHARMACY` (`PHARMACY_ID`),
  KEY `FK_PURCHASE_INVOICE_STATUS` (`INVOICE_STATUS_ID`),
  CONSTRAINT `FK_PURCHASE_INVOICE_APPROVED_BY` FOREIGN KEY (`APPROVED_BY`) REFERENCES `employee` (`EMPLOYEE_ID`) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT `FK_PURCHASE_INVOICE_CREATED_BY` FOREIGN KEY (`CREATED_BY`) REFERENCES `employee` (`EMPLOYEE_ID`) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT `FK_PURCHASE_INVOICE_MODIFIED_BY` FOREIGN KEY (`MODIFIED_BY`) REFERENCES `employee` (`EMPLOYEE_ID`) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT `FK_PURCHASE_INVOICE_PAYMENT_TYPE` FOREIGN KEY (`PAYMENT_TYPE_ID`) REFERENCES `payment_types` (`PAYMENT_TYPE_ID`) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT `FK_PURCHASE_INVOICE_PHARMACY` FOREIGN KEY (`PHARMACY_ID`) REFERENCES `pharmacy` (`PHARMACY_ID`) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT `FK_PURCHASE_INVOICE_STATUS` FOREIGN KEY (`INVOICE_STATUS_ID`) REFERENCES `invoice_status` (`INVOICE_STATUS_ID`) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT `FK_PURCHASE_INVOICE_SUPPLIER` FOREIGN KEY (`SUPPLIER_ID`) REFERENCES `supplier` (`SUPPLIER_ID`) ON DELETE RESTRICT ON UPDATE RESTRICT
)  ;



DROP TABLE IF EXISTS `invoice_item_status`;

CREATE TABLE `invoice_item_status` (
  `INVOICE_ITEM_STATUS_ID` int(11) NOT NULL AUTO_INCREMENT,
  `STATUS` varchar(20) DEFAULT NULL,
  PRIMARY KEY (`INVOICE_ITEM_STATUS_ID`)
) ;


DROP TABLE IF EXISTS `invoice_item_status_xref`;

CREATE TABLE `invoice_item_status_xref` (
  `INVOICE_ITEM_STATUS_XREF_ID` int(11) NOT NULL AUTO_INCREMENT,
  `INVOICE_ITEM_ID` int(11) NOT NULL,
  `INVOICE_ITEM_STATUS_ID` int(11) NOT NULL,
  `QUANTITY` int(11) NOT NULL,
  `COMMENTS` varchar(200) DEFAULT NULL,
  `CREATION_TS` timestamp NULL DEFAULT NULL,
  `CREATION_USER_ID` varchar(50) DEFAULT NULL,
  `LAST_UPDATE_TS` timestamp NULL DEFAULT NULL,
  `LAST_UPDATE_USER_ID` varchar(50) DEFAULT NULL,
  `AUDIT_ID` int(11) DEFAULT NULL,
  PRIMARY KEY (`INVOICE_ITEM_STATUS_XREF_ID`),
  KEY `FK_INVOICE_ITEM` (`INVOICE_ITEM_ID`),
  KEY `FK_INVOICE_ITEM_STATUS` (`INVOICE_ITEM_STATUS_ID`),
  CONSTRAINT `FK_INVOICE_ITEM` FOREIGN KEY (`INVOICE_ITEM_ID`) REFERENCES `invoice_items` (`INVOICE_ITEM_ID`) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT `FK_INVOICE_ITEM_STATUS` FOREIGN KEY (`INVOICE_ITEM_STATUS_ID`) REFERENCES `invoice_item_status` (`INVOICE_ITEM_STATUS_ID`) ON DELETE RESTRICT ON UPDATE RESTRICT
);


DROP TABLE IF EXISTS `invoice_items`;

CREATE TABLE `invoice_items` (
  `INVOICE_ITEM_ID` int(11) NOT NULL AUTO_INCREMENT,
  `INVOICE_ID` int(11) DEFAULT NULL,
  `ITEM_ID` int(11) DEFAULT NULL,
  `PURCHASE_ORDER_ID` int(11) DEFAULT NULL,
  `CREATION_TS` timestamp NULL DEFAULT NULL,
  `CREATION_USER_ID` varchar(50) DEFAULT NULL,
  `LAST_UPDATE_TS` timestamp NULL DEFAULT NULL,
  `LAST_UPDATE_USER_ID` varchar(50) DEFAULT NULL,
  `AUDIT_ID` int(11) DEFAULT NULL,
  `BATCH_NO` varchar(20) DEFAULT NULL,
  `ORDER_QUANTITY` int(11) DEFAULT NULL,
  `QUANTITY_APPROVED` int(11) DEFAULT NULL,
  `UNIT_RATE` double DEFAULT NULL,
  `UNIT_SALE_RATE` double DEFAULT NULL,
  `BONUS` int(11) DEFAULT NULL,
  `DISCOUNT_PERCENTAGE` int(11) DEFAULT NULL,
  `DISCOUNT` int(11) DEFAULT NULL,
  `TOTAL_VALUE` double DEFAULT NULL,
  `ACTUAL_VALUE` double DEFAULT NULL,
  `MANUFACTURE_DT` date DEFAULT NULL,
  `EXPIRY_DT` date DEFAULT NULL,
  `PACK` int(11) DEFAULT NULL,
  `REMARKS` varchar(200) DEFAULT NULL,
  `PURCHASE_TAX_PERCENTAGE` double DEFAULT NULL,
  `PURCHASE_TAX_AMOUNT` double DEFAULT NULL,
  `SALE_TAX_PERCENTAGE` double DEFAULT NULL,
  `SALE_TAX_AMOUNT` double DEFAULT NULL,
  `MRP` double DEFAULT NULL,
  `TOTAL_QUANTITY` int(11) DEFAULT NULL,
  PRIMARY KEY (`INVOICE_ITEM_ID`),
  KEY `FK_PURCHASE_INVOICE_ITEMS` (`ITEM_ID`),
  KEY `PURCHASE_INVOICE_ITEMS_PURCHASE_INVOICE` (`INVOICE_ID`),
  CONSTRAINT `FK_PURCHASE_INVOICE_ITEMS` FOREIGN KEY (`ITEM_ID`) REFERENCES `items` (`ITEM_ID`) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT `PURCHASE_INVOICE_ITEMS_PURCHASE_INVOICE` FOREIGN KEY (`INVOICE_ID`) REFERENCES `invoice` (`INVOICE_ID`) ON DELETE RESTRICT ON UPDATE RESTRICT
) ;

DROP TABLE IF EXISTS `invoice_status`;

CREATE TABLE `invoice_status` (
  `INVOICE_STATUS_ID` int(11) NOT NULL AUTO_INCREMENT,
  `STATUS` varchar(20) DEFAULT NULL,
  PRIMARY KEY (`INVOICE_STATUS_ID`)
) ;


DROP TABLE IF EXISTS `item_alternative`;

CREATE TABLE `item_alternative` (
  `ITEM_ALTERNATIVE_ID` int(11) NOT NULL AUTO_INCREMENT,
  `ITEM_ID` int(11) DEFAULT NULL,
  `ALTERNATIVE_ITEM_ID` int(11) DEFAULT NULL,
  `CREATION_TS` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `CREATION_USER_ID` varchar(50) DEFAULT NULL,
  `LAST_UPDATE_TS` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00',
  `LAST_UPDATE_USER_ID` varchar(50) DEFAULT NULL,
  `AUDIT_ID` int(11) DEFAULT NULL,
  `ACTIVE_S` char(1) CHARACTER SET latin1 COLLATE latin1_swedish_ci DEFAULT 'Y',
  PRIMARY KEY (`ITEM_ALTERNATIVE_ID`),
  KEY `FK_ITEM_ID_idx` (`ITEM_ID`),
  KEY `FK_ALTERNATIVE_ITEM_ID_idx` (`ALTERNATIVE_ITEM_ID`),
  CONSTRAINT `FK_ALTERNATIVE_ITEM_ID` FOREIGN KEY (`ALTERNATIVE_ITEM_ID`) REFERENCES `items` (`ITEM_ID`),
  CONSTRAINT `FK_ITEM_ID` FOREIGN KEY (`ITEM_ID`) REFERENCES `items` (`ITEM_ID`)
);


DROP TABLE IF EXISTS `items`;

CREATE TABLE `items` (
  `ITEM_ID` int(11) NOT NULL AUTO_INCREMENT,
  `ITEM_CD` varchar(20) DEFAULT NULL,
  `ITEM_NM` varchar(100) DEFAULT NULL,
  `ITEM_DESC` mediumtext CHARACTER SET latin1 COLLATE latin1_swedish_ci,
  `MEDICAL_OR_NON_MEDICAL` char(1) CHARACTER SET latin1 COLLATE latin1_swedish_ci DEFAULT 'M',
  `ITEM_GROUP_ID` int(11) DEFAULT NULL,
  `ITEM_GENERIC_NAME_ID` int(11) DEFAULT NULL,
  `ITEM_FORM_ID` int(11) DEFAULT NULL,
  `ITEM_CATEGORIE_ID` int(11) DEFAULT NULL,
  `CREATION_TS` timestamp NULL DEFAULT NULL,
  `CREATION_USER_ID` varchar(50) DEFAULT NULL,
  `LAST_UPDATE_TS` timestamp NULL DEFAULT NULL,
  `LAST_UPDATE_USER_ID` varchar(50) DEFAULT NULL,
  `AUDIT_ID` int(11) DEFAULT NULL,
  `ACTIVE_S` char(1) CHARACTER SET latin1 COLLATE latin1_swedish_ci DEFAULT 'Y',
  `MANUFACTURER_ID` int(11) DEFAULT NULL,
  `SPECIFICATION` varchar(100) DEFAULT NULL,
  `DRUG_DOSE` varchar(20) DEFAULT NULL,
  `IS_ASSET` char(1) CHARACTER SET latin1 COLLATE latin1_swedish_ci DEFAULT NULL,
  `ITEM_USAGE` mediumtext CHARACTER SET latin1 COLLATE latin1_swedish_ci,
  `DRUG_SCHEDULE` char(1) CHARACTER SET latin1 COLLATE latin1_swedish_ci DEFAULT NULL,
  `REORDER_ITEM` char(1) CHARACTER SET latin1 COLLATE latin1_swedish_ci DEFAULT 'Y',
  `PURCHASE_UNIT_OF_MEASUREMENT_ID` int(11) DEFAULT NULL,
  `IS_FORMULARY` char(1) CHARACTER SET latin1 COLLATE latin1_swedish_ci DEFAULT 'N',
  `SPECIALIZATION_ID` int(11) DEFAULT NULL,
  `TEMPERATURE` varchar(20) DEFAULT NULL,
  `BATCH_NO_REQ` char(1) CHARACTER SET latin1 COLLATE latin1_swedish_ci DEFAULT 'Y',
  `REUSABLE` char(1) CHARACTER SET latin1 COLLATE latin1_swedish_ci DEFAULT NULL,
  `IMPORTED` char(1) CHARACTER SET latin1 COLLATE latin1_swedish_ci DEFAULT NULL,
  `HAZARDOUS` char(1) CHARACTER SET latin1 COLLATE latin1_swedish_ci DEFAULT NULL,
  `IS_BILLABLE` char(1) CHARACTER SET latin1 COLLATE latin1_swedish_ci DEFAULT NULL,
  `IS_LOOK_ALIKE` char(1) CHARACTER SET latin1 COLLATE latin1_swedish_ci DEFAULT NULL,
  `IS_SOUND_ALIKE` char(1) CHARACTER SET latin1 COLLATE latin1_swedish_ci DEFAULT NULL,
  `IS_NARCOTIC` char(1) CHARACTER SET latin1 COLLATE latin1_swedish_ci DEFAULT NULL,
  `IS_HIGH_RISK` char(1) CHARACTER SET latin1 COLLATE latin1_swedish_ci DEFAULT NULL,
  `IS_DRUG` char(1) CHARACTER SET latin1 COLLATE latin1_swedish_ci DEFAULT NULL,
  `IS_CRITICAL` char(1) CHARACTER SET latin1 COLLATE latin1_swedish_ci DEFAULT NULL,
  `IS_REVERSE_ANTIBIOTIC` char(1) CHARACTER SET latin1 COLLATE latin1_swedish_ci DEFAULT NULL,
  `IS_NON_REFUNDABLE_ITEM` char(1) CHARACTER SET latin1 COLLATE latin1_swedish_ci DEFAULT NULL,
  `EXPIRY_PROFILE_ID` int(11) DEFAULT NULL,
  `ISSUE_UNIT_OF_MEASUREMENT_ID` int(11) DEFAULT NULL,
  `PACK` varchar(20) DEFAULT NULL,
  `HSN_CODE` varchar(20) DEFAULT NULL,
  `IS_TAX_EXCEMPTED` char(1) CHARACTER SET latin1 COLLATE latin1_swedish_ci DEFAULT NULL,
  `TAX_ID` int(11) DEFAULT NULL,
  `DEFAULT_PO_QTY` int(11) DEFAULT NULL,
  `PO_TERMS` mediumtext CHARACTER SET latin1 COLLATE latin1_swedish_ci,
  `SALE_RATE_FOR_BILLING` varchar(20) DEFAULT NULL,
  `BILLING_MESSAGE` varchar(500) DEFAULT NULL,
  `DIRECTIONS` varchar(500) DEFAULT NULL,
  `INSTRUCTIONS` varchar(500) DEFAULT NULL,
  `EXPIRY_TYPE` varchar(20) DEFAULT NULL,
  `STORAGE_TYPE` varchar(20) DEFAULT NULL,
  `BATCH_NON_BATCH` varchar(20) DEFAULT NULL,
  `SEASONAL_NON_SEASONAL` varchar(20) DEFAULT NULL,
  `CREATED_BY` int(11) DEFAULT NULL,
  `CREATED_DT` date DEFAULT NULL,
  `MODIFIED_BY` int(11) DEFAULT NULL,
  `MODIFIED_DT` date DEFAULT NULL,
  `APPROVED_BY` int(11) DEFAULT NULL,
  `APPROVED_DT` date DEFAULT NULL,
  `REJECTED_BY` int(11) DEFAULT NULL,
  `REJECTED_DT` date DEFAULT NULL,
  `REJECTED_REASON` varchar(200) DEFAULT NULL,
  `DRUG_SHORTAGES` varchar(20) DEFAULT NULL,
  `DRUG_VED` varchar(20) DEFAULT NULL,
  `DRUG_INTERNAL_EXTERNAL_BOTH` varchar(20) DEFAULT NULL,
  PRIMARY KEY (`ITEM_ID`),
  KEY `FK_ITEMS_ITEMS_CATEGORIES` (`ITEM_CATEGORIE_ID`),
  KEY `FK_ITEMS_ITEMS_FORM_ID` (`ITEM_FORM_ID`),
  KEY `FK_ITEMS_ITEMS_GENERIC_NAMES` (`ITEM_GENERIC_NAME_ID`),
  KEY `FK_ITEMS_ITEMS_GROUP_ID` (`ITEM_GROUP_ID`),
  KEY `FK_ITEMS_MANUFACTURER` (`MANUFACTURER_ID`),
  KEY `FK_ITEMS_SPECIALIZATION` (`SPECIALIZATION_ID`),
  KEY `FK_ITEM_APPROVED_BY` (`APPROVED_BY`),
  KEY `FK_ITEM_CREATED_BY` (`CREATED_BY`),
  KEY `FK_ITEM_EXPIRY_PROFILE` (`EXPIRY_PROFILE_ID`),
  KEY `FK_ITEM_MODIFIED_BY` (`MODIFIED_BY`),
  KEY `FK_ITEM_REJECTED_BY` (`REJECTED_BY`),
  KEY `FK_ITEM_TAX` (`TAX_ID`),
  CONSTRAINT `FK_ITEMS_ITEMS_CATEGORIES` FOREIGN KEY (`ITEM_CATEGORIE_ID`) REFERENCES `items_categories` (`ITEM_CATEGORIE_ID`) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT `FK_ITEMS_ITEMS_FORM_ID` FOREIGN KEY (`ITEM_FORM_ID`) REFERENCES `items_forms` (`ITEM_FORM_ID`) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT `FK_ITEMS_ITEMS_GENERIC_NAMES` FOREIGN KEY (`ITEM_GENERIC_NAME_ID`) REFERENCES `items_generic_names` (`ITEM_GENERIC_NAME_ID`) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT `FK_ITEMS_ITEMS_GROUP_ID` FOREIGN KEY (`ITEM_GROUP_ID`) REFERENCES `items_group` (`ITEM_GROUP_ID`) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT `FK_ITEMS_MANUFACTURER` FOREIGN KEY (`MANUFACTURER_ID`) REFERENCES `manufacturer` (`MANUFACTURER_ID`) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT `FK_ITEMS_SPECIALIZATION` FOREIGN KEY (`SPECIALIZATION_ID`) REFERENCES `specialization` (`SPECIALIZATION_ID`) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT `FK_ITEM_APPROVED_BY` FOREIGN KEY (`APPROVED_BY`) REFERENCES `users` (`USER_ID`) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT `FK_ITEM_CREATED_BY` FOREIGN KEY (`CREATED_BY`) REFERENCES `users` (`USER_ID`) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT `FK_ITEM_EXPIRY_PROFILE` FOREIGN KEY (`EXPIRY_PROFILE_ID`) REFERENCES `expiry_profile` (`EXPIRY_PROFILE_ID`) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT `FK_ITEM_MODIFIED_BY` FOREIGN KEY (`MODIFIED_BY`) REFERENCES `users` (`USER_ID`) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT `FK_ITEM_REJECTED_BY` FOREIGN KEY (`REJECTED_BY`) REFERENCES `users` (`USER_ID`) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT `FK_ITEM_TAX` FOREIGN KEY (`TAX_ID`) REFERENCES `tax` (`TAX_ID`) ON DELETE RESTRICT ON UPDATE RESTRICT
) ;


DROP TABLE IF EXISTS `items_bin`;

CREATE TABLE `items_bin` (
  `ITEM_BIN_ID` int(11) NOT NULL AUTO_INCREMENT,
  `ITEM_ID` int(11) DEFAULT NULL,
  `BIN_NO` varchar(20) DEFAULT NULL,
  `CREATION_TS` timestamp NULL DEFAULT NULL,
  `CREATION_USER_ID` varchar(50) DEFAULT NULL,
  `LAST_UPDATE_TS` timestamp NULL DEFAULT NULL,
  `LAST_UPDATE_USER_ID` varchar(50) DEFAULT NULL,
  PRIMARY KEY (`ITEM_BIN_ID`),
  KEY `FK_ITEMS_BIN_ITEM` (`ITEM_ID`),
  CONSTRAINT `FK_ITEMS_BIN_ITEM` FOREIGN KEY (`ITEM_ID`) REFERENCES `items` (`ITEM_ID`) ON DELETE RESTRICT ON UPDATE RESTRICT
);

DROP TABLE IF EXISTS `items_categories`;

CREATE TABLE `items_categories` (
  `ITEM_CATEGORIE_ID` int(11) NOT NULL AUTO_INCREMENT,
  `CATEGORIE_CD` varchar(20) DEFAULT NULL,
  `CATEGORIE_NM` varchar(100) DEFAULT NULL,
  `CATEGORIE_DESC` mediumtext CHARACTER SET latin1 COLLATE latin1_swedish_ci,
  `CREATION_TS` timestamp NULL DEFAULT NULL,
  `CREATION_USER_ID` varchar(50) DEFAULT NULL,
  `LAST_UPDATE_TS` timestamp NULL DEFAULT NULL,
  `LAST_UPDATE_USER_ID` varchar(50) DEFAULT NULL,
  `AUDIT_ID` int(11) DEFAULT NULL,
  `ACTIVE_S` char(1) CHARACTER SET latin1 COLLATE latin1_swedish_ci DEFAULT 'Y',
  `MEDICAL_OR_NON_MEDICAL` char(1) CHARACTER SET latin1 COLLATE latin1_swedish_ci DEFAULT 'M',
  PRIMARY KEY (`ITEM_CATEGORIE_ID`)
) ;



CREATE TABLE `items_supplier` (
  `ITEM_SUPPLIER_ID` int(11) NOT NULL AUTO_INCREMENT,
  `ITEM_ID` int(11) DEFAULT NULL,
  `SUPPLIER_ID` int(11) DEFAULT NULL,
  `CREATION_TS` timestamp NULL DEFAULT NULL,
  `CREATION_USER_ID` varchar(50) DEFAULT NULL,
  `LAST_UPDATE_TS` timestamp NULL DEFAULT NULL,
  `LAST_UPDATE_USER_ID` varchar(50) DEFAULT NULL,
  `ACTIVE_S` char(1) CHARACTER SET latin1 COLLATE latin1_swedish_ci DEFAULT NULL,
  `SUPPLIER_PRIORITY` int(11) DEFAULT NULL,
  `UNIT_RATE` double NOT NULL,
  `DISCOUNT_PERCENTAGE` double NOT NULL,
  `VALIDITY` date NOT NULL,
  PRIMARY KEY (`ITEM_SUPPLIER_ID`),
  KEY `FK_ITEMS_SUPPLIER_ITEMS` (`ITEM_ID`),
  KEY `FK_ITEMS_SUPPLIER_SUPPLIER` (`SUPPLIER_ID`),
  CONSTRAINT `FK_ITEMS_SUPPLIER_SUPPLIER` FOREIGN KEY (`SUPPLIER_ID`) REFERENCES `supplier` (`SUPPLIER_ID`) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT `FK_ITEMS_SUPPLIER_ITEMS` FOREIGN KEY (`ITEM_ID`) REFERENCES `items` (`ITEM_ID`) ON DELETE RESTRICT ON UPDATE RESTRICT
) ;

DROP TABLE IF EXISTS `items_forms`;

CREATE TABLE `items_forms` (
  `ITEM_FORM_ID` int(11) NOT NULL AUTO_INCREMENT,
  `FORM_CD` varchar(20) DEFAULT NULL,
  `FORM` varchar(100) DEFAULT NULL,
  `CREATION_TS` timestamp NULL DEFAULT NULL,
  `CREATION_USER_ID` varchar(50) DEFAULT NULL,
  `LAST_UPDATE_TS` timestamp NULL DEFAULT NULL,
  `LAST_UPDATE_USER_ID` varchar(50) DEFAULT NULL,
  `AUDIT_ID` int(11) DEFAULT NULL,
  `ACTIVE_S` char(1) CHARACTER SET latin1 COLLATE latin1_swedish_ci DEFAULT 'Y',
  `MEDICAL_OR_NON_MEDICAL` char(1) CHARACTER SET latin1 COLLATE latin1_swedish_ci DEFAULT 'M',
  PRIMARY KEY (`ITEM_FORM_ID`)
);


DROP TABLE IF EXISTS `items_generic_names`;

CREATE TABLE `items_generic_names` (
  `ITEM_GENERIC_NAME_ID` int(11) NOT NULL AUTO_INCREMENT,
  `GENERIC_NAME` varchar(500) DEFAULT NULL,
  `CREATION_TS` timestamp NULL DEFAULT NULL,
  `CREATION_USER_ID` varchar(50) DEFAULT NULL,
  `LAST_UPDATE_TS` timestamp NULL DEFAULT NULL,
  `LAST_UPDATE_USER_ID` varchar(50) DEFAULT NULL,
  `AUDIT_ID` int(11) DEFAULT NULL,
  `ACTIVE_S` char(1) CHARACTER SET latin1 COLLATE latin1_swedish_ci DEFAULT 'Y',
  `MEDICAL_OR_NON_MEDICAL` char(1) CHARACTER SET latin1 COLLATE latin1_swedish_ci DEFAULT 'M',
  `ITEM_GROUP_ID` int(11) DEFAULT NULL,
  `GENERIC_CD` varchar(20) DEFAULT NULL,
  PRIMARY KEY (`ITEM_GENERIC_NAME_ID`),
  KEY `FK_ITEM_GENERICS_ITEMS_GROUP` (`ITEM_GROUP_ID`),
  CONSTRAINT `FK_ITEM_GENERICS_ITEMS_GROUP` FOREIGN KEY (`ITEM_GROUP_ID`) REFERENCES `items_group` (`ITEM_GROUP_ID`) ON DELETE RESTRICT ON UPDATE RESTRICT
);


DROP TABLE IF EXISTS `items_group`;

CREATE TABLE `items_group` (
  `ITEM_GROUP_ID` int(11) NOT NULL AUTO_INCREMENT,
  `GROUP_CD` varchar(20) DEFAULT NULL,
  `GROUP_NAME` varchar(100) DEFAULT NULL,
  `GROUP_DESC` mediumtext CHARACTER SET latin1 COLLATE latin1_swedish_ci,
  `CREATION_TS` timestamp NULL DEFAULT NULL,
  `CREATION_USER_ID` varchar(50) DEFAULT NULL,
  `LAST_UPDATE_TS` timestamp NULL DEFAULT NULL,
  `LAST_UPDATE_USER_ID` varchar(50) DEFAULT NULL,
  `AUDIT_ID` int(11) DEFAULT NULL,
  `ACTIVE_S` char(1) CHARACTER SET latin1 COLLATE latin1_swedish_ci DEFAULT 'Y',
  `MEDICAL_OR_NON_MEDICAL` char(1) CHARACTER SET latin1 COLLATE latin1_swedish_ci DEFAULT 'M',
  PRIMARY KEY (`ITEM_GROUP_ID`)
) ;




DROP TABLE IF EXISTS `manufacturer`;

CREATE TABLE `manufacturer` (
  `MANUFACTURER_ID` int(11) NOT NULL AUTO_INCREMENT,
  `NAME` varchar(100) DEFAULT NULL,
  `LICENSE` varchar(100) DEFAULT NULL,
  `PHONE_NBR` varchar(20) DEFAULT NULL,
  `EMAIL_ID` varchar(50) DEFAULT NULL,
  `CREATION_TS` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `CREATION_USER_ID` varchar(50) DEFAULT NULL,
  `LAST_UPDATE_TS` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00',
  `LAST_UPDATE_USER_ID` varchar(50) DEFAULT NULL,
  `ACTIVE_S` char(1) DEFAULT NULL,
  `FAX` varchar(20) DEFAULT NULL,
  `CONTACT_PERSON_EMAIL_ID` varchar(50) DEFAULT NULL,
  `CONTACT_PERSON_PHONE_NBR` varchar(20) DEFAULT NULL,
  `CONTACT_PERSON_FIRST_NM` varchar(50) DEFAULT NULL,
  `WEBSITE` varchar(500) DEFAULT NULL,
  `ADDRESS_LINE1` varchar(250) DEFAULT NULL,
  `ADDRESS_LINE2` varchar(250) DEFAULT NULL,
  `CITY_NM` varchar(50) DEFAULT NULL,
  `ZIP_CD` varchar(10) DEFAULT NULL,
  `AUDIT_ID` int(11) DEFAULT NULL,
  `COUNTRY_ID` int(11) DEFAULT NULL,
  `PROVINCES_ID` int(11) DEFAULT NULL,
  `CONTACT_PERSON_MIDDLE_NM` varchar(50) DEFAULT NULL,
  `CONTACT_PERSON_LAST_NM` varchar(50) DEFAULT NULL,
  PRIMARY KEY (`MANUFACTURER_ID`),
  KEY `FK_MANUFACTURER_COUNTRY_LOOKUP` (`COUNTRY_ID`),
  KEY `FK_MANUFACTURER_PROVINCES_LOOKUP` (`PROVINCES_ID`),
  CONSTRAINT `FK_MANUFACTURER_COUNTRY_LOOKUP` FOREIGN KEY (`COUNTRY_ID`) REFERENCES `country_lookup` (`COUNTRY_ID`) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT `FK_MANUFACTURER_PROVINCES_LOOKUP` FOREIGN KEY (`PROVINCES_ID`) REFERENCES `provinces_lookup` (`PROVINCES_ID`) ON DELETE RESTRICT ON UPDATE RESTRICT
);

DROP TABLE IF EXISTS `membership`;

CREATE TABLE `membership` (
  `MEMBERSHIP_CARD_ID` int(11) NOT NULL AUTO_INCREMENT,
  `CUSTOMER_ID` int(11) DEFAULT NULL,
  `PHARMACY_ID` int(11) DEFAULT NULL,
  `MEMBERSHIP_CARD_NAME` varchar(100) NOT NULL,
  `BONUS_PERCENTAGE` float DEFAULT NULL,
  `DISCOUNT_PERCENTAGE` float DEFAULT NULL,
  `CREDIT_AMOUNT` float DEFAULT NULL,
  `CREDIT_DAYS` float DEFAULT NULL,
  `OFFERS` varchar(100) DEFAULT NULL,
  `CREATION_TS` timestamp NULL DEFAULT NULL,
  `CREATION_USER_ID` varchar(50) DEFAULT NULL,
  `LAST_UPDATE_TS` timestamp NULL DEFAULT NULL,
  `LAST_UPDATE_USER_ID` varchar(50) DEFAULT NULL,
  `AUDIT_ID` int(11) DEFAULT NULL,
  `ACTIVE_S` char(1) CHARACTER SET latin1 COLLATE latin1_swedish_ci DEFAULT 'Y',
  `START_DATE` date DEFAULT NULL,
  `END_DATE` date DEFAULT NULL,
  `DURATION_IN_MONTHS` int(11) NOT NULL,
  PRIMARY KEY (`MEMBERSHIP_CARD_ID`),
  KEY `FK_MEMBERSHIP_CUSTOMER` (`CUSTOMER_ID`),
  KEY `FK_MEMBERSHIP_PHARMACY` (`PHARMACY_ID`),
  CONSTRAINT `FK_MEMBERSHIP_CUSTOMER_LOOKUP` FOREIGN KEY (`CUSTOMER_ID`) REFERENCES `customer` (`CUSTOMER_ID`) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT `FK_MEMBERSHIP_PHARMACY` FOREIGN KEY (`PHARMACY_ID`) REFERENCES `pharmacy` (`PHARMACY_ID`) ON DELETE RESTRICT ON UPDATE RESTRICT
) ;




DROP TABLE IF EXISTS `payment_types`;

CREATE TABLE `payment_types` (
  `PAYMENT_TYPE_ID` int(11) NOT NULL AUTO_INCREMENT,
  `TYPE` varchar(50) DEFAULT NULL,
  PRIMARY KEY (`PAYMENT_TYPE_ID`)
);


DROP TABLE IF EXISTS `pharma_access`;

CREATE TABLE `pharma_access` (
  `PHARMA_ACCESS_ID` int(11) NOT NULL AUTO_INCREMENT,
  `ACCESS_CD` char(2) CHARACTER SET latin1 COLLATE latin1_swedish_ci NOT NULL,
  `ACCESS_NAME` varchar(100) NOT NULL,
  `CREATION_TS` timestamp NULL DEFAULT NULL,
  `CREATION_USER_ID` varchar(50) DEFAULT NULL,
  `LAST_UPDATE_TS` timestamp NULL DEFAULT NULL,
  `LAST_UPDATE_USER_ID` varchar(50) DEFAULT NULL,
  `ACTIVE_S` char(1) CHARACTER SET latin1 COLLATE latin1_swedish_ci DEFAULT 'Y',
  PRIMARY KEY (`PHARMA_ACCESS_ID`)
);


DROP TABLE IF EXISTS `pharmacy`;

CREATE TABLE `pharmacy` (
  `PHARMACY_ID` int(11) NOT NULL AUTO_INCREMENT,
  `PHARMACY_NM` varchar(250) NOT NULL,
  `TAX_ID` varchar(20) NOT NULL,
  `PHONE_NBR` varchar(20) NOT NULL,
  `EMAIL_ID` varchar(50) NOT NULL,
  `AUDIT_ID` int(11) DEFAULT NULL,
  `ACTIVE_S` char(1) NOT NULL DEFAULT 'Y',
  `CREATION_TS` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `CREATION_USER_ID` varchar(50) NOT NULL,
  `LAST_UPDATE_TS` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00',
  `LAST_UPDATE_USER_ID` varchar(50) DEFAULT NULL,
  `AUTHORIZED_PERSON_FIRST_NM` varchar(50) NOT NULL,
  `AUTHORIZED_PERSON_EMAIL_ID` varchar(50) DEFAULT NULL,
  `AUTHORIZED_PERSON_PHONE_NBR` varchar(20) DEFAULT NULL,
  `PHARMACY_LOGO_PATH` blob,
  `WEBSITE_URL` varchar(500) DEFAULT NULL,
  `FAX_NBR` varchar(20) DEFAULT NULL,
  `24_HOURS` char(1) DEFAULT NULL,
  `ADDRESS_LINE1` varchar(250) DEFAULT NULL,
  `ADDRESS_LINE2` varchar(250) DEFAULT NULL,
  `CITY_NM` varchar(50) DEFAULT NULL,
  `PROVINCES_ID` int(11) DEFAULT NULL,
  `COUNTRY_ID` int(11) DEFAULT NULL,
  `ZIP_CD` varchar(10) DEFAULT NULL,
  `AUTHORIZED_PERSON_MIDDLE_NM` varchar(50) DEFAULT NULL,
  `AUTHORIZED_PERSON_LAST_NM` varchar(50) DEFAULT NULL,
  `PURCHASE_ORDER_APPROVAL` char(1) CHARACTER SET latin1 COLLATE latin1_swedish_ci DEFAULT 'Y',
  `MAIN_PHARMACY_ID` int(11) DEFAULT NULL,
  PRIMARY KEY (`PHARMACY_ID`),
  KEY `FK_PHARMACY_ADDRESS_COUNTRY` (`COUNTRY_ID`),
  KEY `FK_PHARMACY_ADDRESS_PROVINCES` (`PROVINCES_ID`),
  KEY `FK_PHARMACY_MAIN_BRANCH` (`MAIN_PHARMACY_ID`),
  CONSTRAINT `FK_PHARMACY_ADDRESS_COUNTRY` FOREIGN KEY (`COUNTRY_ID`) REFERENCES `country_lookup` (`COUNTRY_ID`) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT `FK_PHARMACY_ADDRESS_PROVINCES` FOREIGN KEY (`PROVINCES_ID`) REFERENCES `provinces_lookup` (`PROVINCES_ID`) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT `FK_PHARMACY_MAIN_BRANCH` FOREIGN KEY (`MAIN_PHARMACY_ID`) REFERENCES `pharmacy` (`PHARMACY_ID`) ON DELETE RESTRICT ON UPDATE RESTRICT
) ;

DROP TABLE IF EXISTS `pharmacy_admin`;

CREATE TABLE `pharmacy_admin` (
  `ADMIN_USER_ID` int(11) NOT NULL AUTO_INCREMENT,
  `ADMIN_USER_NM` varchar(50) DEFAULT NULL,
  `PASSWORD` varchar(50) DEFAULT NULL,
  `CREATION_TS` timestamp NULL DEFAULT NULL,
  `CREATION_USER_ID` varchar(50) DEFAULT NULL,
  `LAST_UPDATE_TS` timestamp NULL DEFAULT NULL,
  `LAST_UPDATE_USER_ID` varchar(50) DEFAULT NULL,
  `AUDIT_ID` int(11) DEFAULT NULL,
  PRIMARY KEY (`ADMIN_USER_ID`)
) ;


DROP TABLE IF EXISTS `pharmacy_purchase_order_approval_process`;

CREATE TABLE `pharmacy_purchase_order_approval_process` (
  `PHARMACY_PURCHASE_ORDER_APPROVAL_PROCESS_ID` int(11) NOT NULL AUTO_INCREMENT,
  `PHARMACY_ID` int(11) NOT NULL,
  `TYPE` varchar(50) DEFAULT NULL,
  `DESCRIPTION` varchar(200) DEFAULT NULL,
  `MIN_AMOUNT` double DEFAULT NULL,
  `MAX_AMOUNT` double DEFAULT NULL,
  `CREATION_TS` timestamp NULL DEFAULT NULL,
  `CREATION_USER_ID` varchar(50) DEFAULT NULL,
  `LAST_UPDATE_TS` timestamp NULL DEFAULT NULL,
  `LAST_UPDATE_USER_ID` varchar(50) DEFAULT NULL,
  `APPROVAL_USER` int(11) DEFAULT NULL,
  `AUDIT_ID` int(11) DEFAULT NULL,
  PRIMARY KEY (`PHARMACY_PURCHASE_ORDER_APPROVAL_PROCESS_ID`),
  KEY `FK_PHARMACY_PURCHASE_ORDER_PHARMACY` (`PHARMACY_ID`),
  CONSTRAINT `FK_PHARMACY_PURCHASE_ORDER_PHARMACY` FOREIGN KEY (`PHARMACY_ID`) REFERENCES `pharmacy` (`PHARMACY_ID`) ON DELETE RESTRICT ON UPDATE RESTRICT
) ;



DROP TABLE IF EXISTS `pharmacy_roles`;

CREATE TABLE `pharmacy_roles` (
  `ROLE_ID` int(11) NOT NULL AUTO_INCREMENT,
  `ROLE_NM` varchar(20) DEFAULT NULL,
  `DESCRIPTION` varchar(200) DEFAULT NULL,
  `CREATION_TS` timestamp NULL DEFAULT NULL,
  `CREATION_USER_ID` varchar(50) DEFAULT NULL,
  `LAST_UPDATE_TS` timestamp NULL DEFAULT NULL,
  `LAST_UPDATE_USER_ID` varchar(50) DEFAULT NULL,
  PRIMARY KEY (`ROLE_ID`)
);


DROP TABLE IF EXISTS `pharmacy_setup`;

CREATE TABLE `pharmacy_setup` (
  `SETUP_ID` int(11) NOT NULL AUTO_INCREMENT,
  `ADMIN_USER_ID` int(11) NOT NULL,
  `CREATION_TS` timestamp NULL DEFAULT NULL,
  `CREATION_USER_ID` varchar(50) DEFAULT NULL,
  `LAST_UPDATE_TS` timestamp NULL DEFAULT NULL,
  `LAST_UPDATE_USER_ID` varchar(50) DEFAULT NULL,
  `AUDIT_ID` int(11) DEFAULT NULL,
  PRIMARY KEY (`SETUP_ID`),
  KEY `FK_ADMIN_ID_LOOKUP_idx` (`ADMIN_USER_ID`),
  CONSTRAINT `FK_ADMIN_ID_LOOKUP` FOREIGN KEY (`ADMIN_USER_ID`) REFERENCES `employee` (`EMPLOYEE_ID`)
) ;



DROP TABLE IF EXISTS `pharmacy_stock_points`;

CREATE TABLE `pharmacy_stock_points` (
  `PHARMACY_STOCK_POINTS_ID` int(11) NOT NULL AUTO_INCREMENT,
  `PHARMACY_BRANCH_ID` int(11) DEFAULT NULL,
  `CREATION_TS` timestamp NULL DEFAULT NULL,
  `CREATION_USER_ID` varchar(50) DEFAULT NULL,
  `LAST_UPDATE_TS` timestamp NULL DEFAULT NULL,
  `LAST_UPDATE_USER_ID` varchar(50) DEFAULT NULL,
  `ACTIVE_S` char(1) CHARACTER SET latin1 COLLATE latin1_swedish_ci DEFAULT 'Y',
  `STOCK_POINT_NM` varchar(50) DEFAULT NULL,
  `STOCK_POINT_TYPE` varchar(20) DEFAULT NULL,
  `STOCK_POINT_ALIAS_NM` varchar(20) DEFAULT NULL,
  `TRANSACTION_TYPE` char(2) CHARACTER SET latin1 COLLATE latin1_swedish_ci DEFAULT NULL,
  `RETURN_APPLICABLE` char(1) CHARACTER SET latin1 COLLATE latin1_swedish_ci DEFAULT 'Y',
  `OT_TAX_APPLICABLE` char(1) CHARACTER SET latin1 COLLATE latin1_swedish_ci DEFAULT NULL,
  `PAYMENT_TYPE` varchar(20) DEFAULT NULL,
  `DISCOUNT_FACILITY` char(1) CHARACTER SET latin1 COLLATE latin1_swedish_ci DEFAULT NULL,
  PRIMARY KEY (`PHARMACY_STOCK_POINTS_ID`),
  KEY `FK_PHARMACY_STOCK_POINTS_PHARMACY_BRANCH` (`PHARMACY_BRANCH_ID`)
) ;



DROP TABLE IF EXISTS `provider`;

CREATE TABLE `provider` (
  `PROVIDER_ID` int(11) NOT NULL AUTO_INCREMENT,
  `FIRST_NM` varchar(50) DEFAULT NULL,
  `LAST_NM` varchar(50) DEFAULT NULL,
  `PHONE_NBR` varchar(20) DEFAULT NULL,
  `EMAIL_ID` varchar(50) DEFAULT NULL,
  `CREATION_TS` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `CREATION_USER_ID` varchar(50) DEFAULT NULL,
  `LAST_UPDATE_TS` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00',
  `LAST_UPDATE_USER_ID` varchar(50) DEFAULT NULL,
  `ACTIVE_S` char(1) CHARACTER SET latin1 COLLATE latin1_swedish_ci DEFAULT 'Y',
  `ADDRESS_LINE1` varchar(250) DEFAULT NULL,
  `ADDRESS_LINE2` varchar(250) DEFAULT NULL,
  `CITY_NM` varchar(50) DEFAULT NULL,
  `ZIP_CD` varchar(10) DEFAULT NULL,
  `CREDIT` varchar(20) DEFAULT NULL,
  `LICENSE_NUMBER` varchar(20) DEFAULT NULL,
  `DEA_NUMBER` varchar(20) DEFAULT NULL,
  `GENDER_CD` char(1) DEFAULT NULL,
  `DOB` date DEFAULT NULL,
  `SPECIALITY` varchar(20) DEFAULT NULL,
  `AUDIT_ID` int(11) DEFAULT NULL,
  `PROVIDER_TYPE_LOOKUP_ID` int(11) DEFAULT NULL,
  `COUNTRY_ID` int(11) DEFAULT NULL,
  `PROVINCES_ID` int(11) DEFAULT NULL,
  `MIDDLE_NM` varchar(50) DEFAULT NULL,
  `HOSPITAL_ID` int(11) DEFAULT NULL,
  PRIMARY KEY (`PROVIDER_ID`),
  KEY `FK_PROVIDER_COUNTRY_LOOKUP` (`COUNTRY_ID`),
  KEY `FK_PROVIDER_PROVIDER_LOOKUP_ID` (`PROVIDER_TYPE_LOOKUP_ID`),
  KEY `FK_PROVIDER_PROVINCES_LOOKUP` (`PROVINCES_ID`),
  KEY `FK_PROVIDER_HOSPITAL_ID` (`HOSPITAL_ID`),
  CONSTRAINT `FK_PROVIDER_COUNTRY_LOOKUP` FOREIGN KEY (`COUNTRY_ID`) REFERENCES `country_lookup` (`COUNTRY_ID`) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT `FK_PROVIDER_HOSPITAL_ID` FOREIGN KEY (`HOSPITAL_ID`) REFERENCES `hospital` (`HOSPITAL_ID`) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT `FK_PROVIDER_PROVIDER_LOOKUP_ID` FOREIGN KEY (`PROVIDER_TYPE_LOOKUP_ID`) REFERENCES `provider_type_lookup` (`PROVIDER_TYPE_LOOKUP_ID`) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT `FK_PROVIDER_PROVINCES_LOOKUP` FOREIGN KEY (`PROVINCES_ID`) REFERENCES `provinces_lookup` (`PROVINCES_ID`) ON DELETE RESTRICT ON UPDATE RESTRICT
) ;


DROP TABLE IF EXISTS `provider_hospitals`;

CREATE TABLE `provider_hospitals` (
  `PROVIDER_HOSPITAL_ID` int(11) NOT NULL AUTO_INCREMENT,
  `PROVIDER_ID` int(11) DEFAULT NULL,
  `HOSPITAL_ID` int(11) DEFAULT NULL,
  `CREATION_TS` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `CREATION_USER_ID` varchar(50) DEFAULT NULL,
  `LAST_UPDATE_TS` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00',
  `LAST_UPDATE_USER_ID` varchar(50) DEFAULT NULL,
  `AUDIT_ID` int(11) DEFAULT NULL,
  PRIMARY KEY (`PROVIDER_HOSPITAL_ID`),
  KEY `FK_PROVIDER_HOSPITALS_PROVIDER` (`PROVIDER_ID`),
  KEY `FK_PROVIDER_HOSPITALS_HOSPITALS` (`HOSPITAL_ID`),
  CONSTRAINT `FK_PROVIDER_HOSPITALS_HOSPITALS` FOREIGN KEY (`HOSPITAL_ID`) REFERENCES `hospital` (`HOSPITAL_ID`) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT `FK_PROVIDER_HOSPITALS_PROVIDER` FOREIGN KEY (`PROVIDER_ID`) REFERENCES `provider` (`PROVIDER_ID`) ON DELETE RESTRICT ON UPDATE RESTRICT
) ;


DROP TABLE IF EXISTS `provider_type_lookup`;

CREATE TABLE `provider_type_lookup` (
  `PROVIDER_TYPE_LOOKUP_ID` int(11) NOT NULL AUTO_INCREMENT,
  `PROVIDER_TYPE_CD` char(2) CHARACTER SET latin1 COLLATE latin1_swedish_ci DEFAULT NULL,
  `PROVIDER_TYPE_DESC` varchar(250) DEFAULT NULL,
  `CREATION_TS` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `CREATION_USER_ID` varchar(50) NOT NULL,
  `LAST_UPDATE_TS` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00',
  `LAST_UPDATE_USER_ID` varchar(50) DEFAULT NULL,
  `AUDIT_ID` int(11) DEFAULT NULL,
  PRIMARY KEY (`PROVIDER_TYPE_LOOKUP_ID`)
) ;




DROP TABLE IF EXISTS `provinces_lookup`;

CREATE TABLE `provinces_lookup` (
  `PROVINCES_ID` int(11) NOT NULL AUTO_INCREMENT,
  `AUDIT_ID` int(11) DEFAULT NULL,
  `CREATION_TS` timestamp NULL DEFAULT NULL,
  `CREATION_USER_ID` varchar(50) DEFAULT NULL,
  `LAST_UPDATE_TS` timestamp NULL DEFAULT NULL,
  `LAST_UPDATE_USER_ID` varchar(50) DEFAULT NULL,
  `PROVINCES_NM` varchar(255) DEFAULT NULL,
  `COUNTRY_ID` int(11) DEFAULT NULL,
  PRIMARY KEY (`PROVINCES_ID`),
  KEY `FK_PROVINCES_LOOKUP_COUNTRY` (`COUNTRY_ID`),
  CONSTRAINT `FK_PROVINCES_LOOKUP_COUNTRY` FOREIGN KEY (`COUNTRY_ID`) REFERENCES `country_lookup` (`COUNTRY_ID`)
) ;


DROP TABLE IF EXISTS `purchase_order`;

CREATE TABLE `purchase_order` (
  `PURCHASE_ORDER_ID` int(11) NOT NULL AUTO_INCREMENT,
  `PURCHASE_ORDER_NO` varchar(20) DEFAULT NULL,
  `SUPPLIER_ID` int(11) NOT NULL,
  `QUOTATION_ID` int(11) DEFAULT NULL,
  `PURCHASE_ORDER_DT` date DEFAULT NULL,
  `REQUEST_DT` date DEFAULT NULL,
  `PURCHASE_ORDER_STATUS_ID` int(1) DEFAULT NULL,
  `REMARKS` varchar(200) DEFAULT NULL,
  `CREATED_BY` int(11) DEFAULT NULL,
  `EMERGENCY` char(1) CHARACTER SET latin1 COLLATE latin1_swedish_ci DEFAULT NULL,
  `CREATION_TS` timestamp NULL DEFAULT NULL,
  `CREATION_USER_ID` varchar(50) DEFAULT NULL,
  `LAST_UPDATE_TS` timestamp NULL DEFAULT NULL,
  `LAST_UPDATE_USER_ID` varchar(50) DEFAULT NULL,
  `MODIFIED_BY` int(11) DEFAULT NULL,
  `MODIFIED_DT` date DEFAULT NULL,
  `APPROVED_BY` int(11) DEFAULT NULL,
  `APPROVED_DT` date DEFAULT NULL,
  `REJECTED_BY` int(11) DEFAULT NULL,
  `REJECTED_DT` date DEFAULT NULL,
  `SENT_BY` int(11) DEFAULT NULL,
  `SENT_DT` date DEFAULT NULL,
  `AUDIT_ID` int(11) DEFAULT NULL,
  `PHARMACY_ID` int(11) DEFAULT NULL,
  `PO_AMOUNT` double DEFAULT NULL,
  `DELIVERY_TIME` int(11) DEFAULT NULL,
  `PAYMENT_TIME` int(11) DEFAULT NULL,
  `PO_NATURE` varchar(20) DEFAULT NULL,
  `PO_CATEGORY` varchar(20) DEFAULT NULL,
  `PO_TERM` varchar(20) DEFAULT NULL,
  `ADVANCE` double DEFAULT NULL,
  `DISCOUNT` double DEFAULT NULL,
  `DISCOUNT_PERCENTAGE` float DEFAULT NULL,
  `OTHER_CHARGES` double DEFAULT NULL,
  `VARIATION_TYPE` varchar(20) DEFAULT NULL,
  `REQUESTED_BY` int(11) DEFAULT NULL,
  `DELIVERY_TYPE_ID` int(11) DEFAULT NULL,
  `MEDICAL_OR_NON_MEDICAL` char(1) CHARACTER SET latin1 COLLATE latin1_swedish_ci DEFAULT NULL,
  `CASH` char(1) CHARACTER SET latin1 COLLATE latin1_swedish_ci DEFAULT NULL,
  `SHIPPING_ADDRESS` varchar(500) DEFAULT NULL,
  PRIMARY KEY (`PURCHASE_ORDER_ID`),
  KEY `FK_PURCHASE_ORDER_APPROVED_BY` (`APPROVED_BY`),
  KEY `FK_PURCHASE_ORDER_CREATED_BY` (`CREATED_BY`),
  KEY `FK_PURCHASE_ORDER_DELIVERY_TYPE` (`DELIVERY_TYPE_ID`),
  KEY `FK_PURCHASE_ORDER_SUPPLIER` (`SUPPLIER_ID`),
  KEY `FK_PURCHASE_ORDER_MODIFIED_BY` (`MODIFIED_BY`),
  KEY `FK_PURCHASE_ORDER_PHARMACY` (`PHARMACY_ID`),
  KEY `FK_PURCHASE_ORDER_QUOTATION` (`QUOTATION_ID`),
  KEY `FK_PURCHASE_ORDER_REQUESTED_BY` (`REQUESTED_BY`),
  KEY `FK_PURCHASE_ORDER_STATUS` (`PURCHASE_ORDER_STATUS_ID`),
  KEY `FK_PURCHASE_ORDER_SENT_BY` (`SENT_BY`),
  KEY `FK_PURCHASE_ORDER_REJECTED_BY` (`REJECTED_BY`),
  CONSTRAINT `FK_PURCHASE_ORDER_APPROVED_BY` FOREIGN KEY (`APPROVED_BY`) REFERENCES `employee` (`EMPLOYEE_ID`) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT `FK_PURCHASE_ORDER_CREATED_BY` FOREIGN KEY (`CREATED_BY`) REFERENCES `employee` (`EMPLOYEE_ID`) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT `FK_PURCHASE_ORDER_DELIVERY_TYPE` FOREIGN KEY (`DELIVERY_TYPE_ID`) REFERENCES `delivery_types` (`DELIVERY_TYPE_ID`) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT `FK_PURCHASE_ORDER_MODIFIED_BY` FOREIGN KEY (`MODIFIED_BY`) REFERENCES `employee` (`EMPLOYEE_ID`) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT `FK_PURCHASE_ORDER_PHARMACY` FOREIGN KEY (`PHARMACY_ID`) REFERENCES `pharmacy` (`PHARMACY_ID`) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT `FK_PURCHASE_ORDER_QUOTATION` FOREIGN KEY (`QUOTATION_ID`) REFERENCES `quotation` (`QUOTATION_ID`) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT `FK_PURCHASE_ORDER_REJECTED_BY` FOREIGN KEY (`REJECTED_BY`) REFERENCES `employee` (`EMPLOYEE_ID`) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT `FK_PURCHASE_ORDER_REQUESTED_BY` FOREIGN KEY (`REQUESTED_BY`) REFERENCES `employee` (`EMPLOYEE_ID`) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT `FK_PURCHASE_ORDER_SENT_BY` FOREIGN KEY (`SENT_BY`) REFERENCES `employee` (`EMPLOYEE_ID`) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT `FK_PURCHASE_ORDER_STATUS` FOREIGN KEY (`PURCHASE_ORDER_STATUS_ID`) REFERENCES `purchase_order_status` (`PURCHASE_ORDER_STATUS_ID`) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT `FK_PURCHASE_ORDER_SUPPLIER` FOREIGN KEY (`SUPPLIER_ID`) REFERENCES `supplier` (`SUPPLIER_ID`) ON DELETE RESTRICT ON UPDATE RESTRICT
) ;


DROP TABLE IF EXISTS `purchase_order_items`;

CREATE TABLE `purchase_order_items` (
  `PURCHASE_ORDER_ITEM_ID` int(11) NOT NULL AUTO_INCREMENT,
  `PURCHASE_ORDER_ID` int(11) NOT NULL,
  `ITEM_ID` int(11) NOT NULL,
  `QUANTITY` int(11) NOT NULL,
  `REMARKS` varchar(200) DEFAULT NULL,
  `STATUS` char(1) CHARACTER SET latin1 COLLATE latin1_swedish_ci DEFAULT NULL,
  `CREATION_TS` timestamp NULL DEFAULT NULL,
  `CREATION_USER_ID` varchar(50) DEFAULT NULL,
  `LAST_UPDATE_TS` timestamp NULL DEFAULT NULL,
  `LAST_UPDATE_USER_ID` varchar(50) DEFAULT NULL,
  `AUDIT_ID` int(11) DEFAULT NULL,
  `UNIT_RATE` double NOT NULL,
  `UNIT_SALE_RATE` double NOT NULL,
  `BONUS` double DEFAULT NULL,
  `DISCOUNT_PERCENTAGE` float DEFAULT NULL,
  `TAX` double DEFAULT NULL,
  `DISCOUNT` double DEFAULT NULL,
  `TOTAL_VALUE` double DEFAULT NULL,
  `TOTAL_QUANTITY` int(11) DEFAULT NULL,
  `ACTUAL_VALUE` double DEFAULT NULL,
  `PACK` int(11) DEFAULT NULL,
  PRIMARY KEY (`PURCHASE_ORDER_ITEM_ID`),
  KEY `FK_PURCHASE_ORDER_ITEMS_ITEMS` (`ITEM_ID`),
  KEY `FK_PURCHASE_ORDER_ITEMS_PURCHASE_ORDER` (`PURCHASE_ORDER_ID`),
  CONSTRAINT `FK_PURCHASE_ORDER_ITEMS_ITEMS` FOREIGN KEY (`ITEM_ID`) REFERENCES `items` (`ITEM_ID`) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT `FK_PURCHASE_ORDER_ITEMS_PURCHASE_ORDER` FOREIGN KEY (`PURCHASE_ORDER_ID`) REFERENCES `purchase_order` (`PURCHASE_ORDER_ID`) ON DELETE RESTRICT ON UPDATE RESTRICT
)  ;




DROP TABLE IF EXISTS `purchase_order_status`;

CREATE TABLE `purchase_order_status` (
  `PURCHASE_ORDER_STATUS_ID` int(11) NOT NULL AUTO_INCREMENT,
  `STATUS` varchar(20) DEFAULT NULL,
  PRIMARY KEY (`PURCHASE_ORDER_STATUS_ID`)
) ;



DROP TABLE IF EXISTS `quotation`;

CREATE TABLE `quotation` (
  `QUOTATION_ID` int(11) NOT NULL AUTO_INCREMENT,
  `QUOTATION_NO` varchar(20) DEFAULT NULL,
  `QUOTATION_DT` date DEFAULT NULL,
  `CREATED_BY` int(11) DEFAULT NULL,
  `DESCRIPTION` varchar(200) DEFAULT NULL,
  `CREATION_TS` timestamp NULL DEFAULT NULL,
  `CREATION_USER_ID` varchar(50) DEFAULT NULL,
  `LAST_UPDATE_TS` timestamp NULL DEFAULT NULL,
  `LAST_UPDATE_USER_ID` varchar(50) DEFAULT NULL,
  `AUDIT_ID` int(11) DEFAULT NULL,
  `PHARMACY_ID` int(11) DEFAULT NULL,
  `QUOTATION_STATUS_ID` int(11) DEFAULT NULL,
  `SENT_BY` int(11) DEFAULT NULL,
  `SENT_DT` date DEFAULT NULL,
  `REQUESTED_BY` int(11) DEFAULT NULL,
  `MODIFIED_BY` int(11) DEFAULT NULL,
  `MODIFIED_DT` date DEFAULT NULL,
  `APPROVED_BY` int(11) DEFAULT NULL,
  `APPROVED_DT` date DEFAULT NULL,
  `QUOTATION_EXPIRY_DT` date DEFAULT NULL,
  `CANCELLED_REASON` varchar(200) DEFAULT NULL,
  `REJECTED_BY` int(11) DEFAULT NULL,
  `REJECTED_DT` date DEFAULT NULL,
  `REJECTED_REASON` varchar(200) DEFAULT NULL,
  `QUOTATION_SEND_MODE` varchar(20) DEFAULT NULL,
  PRIMARY KEY (`QUOTATION_ID`),
  KEY `FK_QUOTATION_CREATED_BY` (`CREATED_BY`),
  KEY `FK_QUOTATION_PHARMACY_ID` (`PHARMACY_ID`),
  KEY `FK_QUOTATION_STATUS` (`QUOTATION_STATUS_ID`),
  KEY `FK_QUOTATION_SENT_BY` (`SENT_BY`),
  KEY `FK_QUOTATION_REQUESTED_BY` (`REQUESTED_BY`),
  KEY `FK_QUOTATION_APPROVED_BY` (`APPROVED_BY`),
  KEY `FK_QUOTATION_REJECTED_BY` (`REJECTED_BY`),
  KEY `FK_QUOTATION_MODIFIED_BY` (`MODIFIED_BY`),
  CONSTRAINT `FK_QUOTATION_APPROVED_BY` FOREIGN KEY (`APPROVED_BY`) REFERENCES `employee` (`EMPLOYEE_ID`) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT `FK_QUOTATION_CREATED_BY` FOREIGN KEY (`CREATED_BY`) REFERENCES `employee` (`EMPLOYEE_ID`) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT `FK_QUOTATION_MODIFIED_BY` FOREIGN KEY (`MODIFIED_BY`) REFERENCES `employee` (`EMPLOYEE_ID`) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT `FK_QUOTATION_PHARMACY_ID` FOREIGN KEY (`PHARMACY_ID`) REFERENCES `pharmacy` (`PHARMACY_ID`) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT `FK_QUOTATION_REJECTED_BY` FOREIGN KEY (`REJECTED_BY`) REFERENCES `employee` (`EMPLOYEE_ID`) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT `FK_QUOTATION_REQUESTED_BY` FOREIGN KEY (`REQUESTED_BY`) REFERENCES `employee` (`EMPLOYEE_ID`) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT `FK_QUOTATION_SENT_BY` FOREIGN KEY (`SENT_BY`) REFERENCES `employee` (`EMPLOYEE_ID`) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT `FK_QUOTATION_STATUS` FOREIGN KEY (`QUOTATION_STATUS_ID`) REFERENCES `quotation_status` (`QUOTATION_STATUS_ID`) ON DELETE RESTRICT ON UPDATE RESTRICT
);



DROP TABLE IF EXISTS `quotation_item_status`;

CREATE TABLE `quotation_item_status` (
  `QUOTATION_ITEM_STATUS_ID` int(11) NOT NULL AUTO_INCREMENT,
  `STATUS` varchar(20) DEFAULT NULL,
  PRIMARY KEY (`QUOTATION_ITEM_STATUS_ID`)
) ;



DROP TABLE IF EXISTS `quotation_items`;

CREATE TABLE `quotation_items` (
  `QUOTATION_ITEM_ID` int(11) NOT NULL AUTO_INCREMENT,
  `QUOTATION_ID` int(11) NOT NULL,
  `ITEM_ID` int(11) NOT NULL,
  `QUANTITY` int(11) DEFAULT NULL,
  `REMARKS` varchar(200) DEFAULT NULL,
  `STATUS` int(1) DEFAULT NULL,
  `CREATION_TS` timestamp NULL DEFAULT NULL,
  `CREATION_USER_ID` varchar(50) DEFAULT NULL,
  `LAST_UPDATE_TS` timestamp NULL DEFAULT NULL,
  `LAST_UPDATE_USER_ID` varchar(50) DEFAULT NULL,
  `AUDIT_ID` int(11) DEFAULT NULL,
  `supplier_ID` int(11) DEFAULT NULL,
  `DISCOUNT` double DEFAULT NULL,
  `DISCOUNT_PERCENTAGE` float DEFAULT NULL,
  `BONUS` int(11) DEFAULT NULL,
  `DELIVERY_TIME` int(11) DEFAULT NULL,
  `UNIT_PURCHASE_PRICE` double DEFAULT NULL,
  `MRP` double DEFAULT NULL,
  `NET_CREDIT` int(11) DEFAULT NULL,
  `PAYMENT_DAYS` int(11) DEFAULT NULL,
  `CONDITIONS` mediumtext CHARACTER SET latin1 COLLATE latin1_swedish_ci,
  `ADVANCE` double DEFAULT NULL,
  `DELETE_S` char(1) CHARACTER SET latin1 COLLATE latin1_swedish_ci DEFAULT 'N',
  `APPROVED_BY` int(11) DEFAULT NULL,
  `PRIORITY` int(11) DEFAULT NULL,
  `MIN_UNITS` int(11) DEFAULT NULL,
  `MAX_UNITS` int(11) DEFAULT NULL,
  `PRICE_EFFECTIVE_FROM_DT` date DEFAULT NULL,
  `PRICE_EFFECTIVE_TO_DT` date DEFAULT NULL,
  `TAX_INCLUDE_EXCLUDE` varchar(20) DEFAULT NULL,
  `UNIT_SALE_PRICE` double DEFAULT NULL,
  `EXCISE_DUTY` float DEFAULT NULL,
  `EXCISE_DUTY_INCLUDE_EXCLUDE` varchar(20) DEFAULT NULL,
  `PO_TERMS` mediumtext CHARACTER SET latin1 COLLATE latin1_swedish_ci,
  `TAX_ID` int(11) DEFAULT NULL,
  PRIMARY KEY (`QUOTATION_ITEM_ID`),
  KEY `FK_QUOTATION_ITEMS_APPROVED_BY` (`APPROVED_BY`),
  KEY `FK_QUOTATION_ITEMS_SUPPLIER` (`SUPPLIER_ID`),
  KEY `FK_QUOTATION_ITEMS_ITEMS` (`ITEM_ID`),
  KEY `FK_QUOTATION_ITEMS_QUOTATION` (`QUOTATION_ID`),
  KEY `FK_QUOTATION_ITEMS_STATUS` (`STATUS`),
  KEY `FK_QUOTATION_ITEM_TAX` (`TAX_ID`),
  CONSTRAINT `FK_QUOTATION_ITEMS_APPROVED_BY` FOREIGN KEY (`APPROVED_BY`) REFERENCES `users` (`USER_ID`) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT `FK_QUOTATION_ITEMS_SUPPLIER` FOREIGN KEY (`SUPPLIER_ID`) REFERENCES `supplier` (`SUPPLIER_ID`) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT `FK_QUOTATION_ITEMS_ITEMS` FOREIGN KEY (`ITEM_ID`) REFERENCES `items` (`ITEM_ID`) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT `FK_QUOTATION_ITEMS_QUOTATION` FOREIGN KEY (`QUOTATION_ID`) REFERENCES `quotation` (`QUOTATION_ID`) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT `FK_QUOTATION_ITEMS_STATUS` FOREIGN KEY (`STATUS`) REFERENCES `quotation_item_status` (`QUOTATION_ITEM_STATUS_ID`) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT `FK_QUOTATION_ITEM_TAX` FOREIGN KEY (`TAX_ID`) REFERENCES `tax` (`TAX_ID`) ON DELETE RESTRICT ON UPDATE RESTRICT
) ;


DROP TABLE IF EXISTS `quotation_status`;

CREATE TABLE `quotation_status` (
  `QUOTATION_STATUS_ID` int(11) NOT NULL AUTO_INCREMENT,
  `STATUS` varchar(20) DEFAULT NULL,
  PRIMARY KEY (`QUOTATION_STATUS_ID`)
);


DROP TABLE IF EXISTS `return_credit_type`;

CREATE TABLE `return_credit_type` (
  `RETURN_CREDIT_TYPE_ID` int(11) NOT NULL AUTO_INCREMENT,
  `TYPE` varchar(20) DEFAULT NULL,
  `AUDIT_ID` int(11) DEFAULT NULL,
  `CREATION_TS` timestamp NULL DEFAULT NULL,
  `CREATION_USER_ID` varchar(50) DEFAULT NULL,
  `LAST_UPDATE_TS` timestamp NULL DEFAULT NULL,
  `LAST_UPDATE_USER_ID` varchar(50) DEFAULT NULL,
  PRIMARY KEY (`RETURN_CREDIT_TYPE_ID`)
) ;


DROP TABLE IF EXISTS `roles`;

CREATE TABLE `roles` (
  `ROLE_ID` int(11) NOT NULL AUTO_INCREMENT,
  `ROLE_NM` varchar(20) DEFAULT NULL,
  `DESCRIPTION` varchar(200) DEFAULT NULL,
  `CREATION_TS` timestamp NULL DEFAULT NULL,
  `CREATION_USER_ID` varchar(50) DEFAULT NULL,
  `LAST_UPDATE_TS` timestamp NULL DEFAULT NULL,
  `LAST_UPDATE_USER_ID` varchar(50) DEFAULT NULL,
  PRIMARY KEY (`ROLE_ID`)
) ;


DROP TABLE IF EXISTS `specialization`;

CREATE TABLE `specialization` (
  `SPECIALIZATION_ID` int(11) NOT NULL AUTO_INCREMENT,
  `SPECIALIZATION_CD` varchar(20) DEFAULT NULL,
  `SPECIALIZATION_NAME` varchar(100) DEFAULT NULL,
  `SPECIALIZATION_DESC` mediumtext CHARACTER SET latin1 COLLATE latin1_swedish_ci,
  `CREATION_TS` timestamp NULL DEFAULT NULL,
  `CREATION_USER_ID` varchar(50) DEFAULT NULL,
  `LAST_UPDATE_TS` timestamp NULL DEFAULT NULL,
  `LAST_UPDATE_USER_ID` varchar(50) DEFAULT NULL,
  `AUDIT_ID` int(11) DEFAULT NULL,
  `ACTIVE_S` char(1) CHARACTER SET latin1 COLLATE latin1_swedish_ci DEFAULT 'y',
  PRIMARY KEY (`SPECIALIZATION_ID`)
) ;


DROP TABLE IF EXISTS `stock`;

CREATE TABLE `stock` (
  `STOCK_ID` int(11) NOT NULL AUTO_INCREMENT,
  `INVOICE_ID` int(11) DEFAULT NULL,
  `ITEM_ID` int(11) DEFAULT NULL,
  `PHARMACY_ID` int(11) DEFAULT NULL,
  `QUANTITY` int(11) DEFAULT NULL,
  `UNIT_SALE_RATE` double DEFAULT NULL,
  `MRP` double DEFAULT NULL,
  `MARGIN` double DEFAULT NULL,
  `SALE_DISCOUNT_PERCENTAGE` double DEFAULT NULL,
  `SALE_DISCOUNT_AMOUNT` double DEFAULT NULL,
  `AUDIT_ID` int(11) DEFAULT NULL,
  `CREATION_TS` timestamp NULL DEFAULT NULL,
  `CREATION_USER_ID` varchar(50) DEFAULT NULL,
  `LAST_UPDATE_TS` timestamp NULL DEFAULT NULL,
  `LAST_UPDATE_USER_ID` varchar(50) DEFAULT NULL,
  `MANUFACTURE_DT` date DEFAULT NULL,
  `EXPIRY_DT` date DEFAULT NULL,
  `BATCH_NO` varchar(20) DEFAULT NULL,
  `PURCHASE_DISCOUNT_AMOUNT` double DEFAULT NULL,
  `PURCHASE_DISCOUNT_PERCENTAGE` double DEFAULT NULL,
  `RACK` varchar(50) DEFAULT NULL,
  `UNIT_PURCHASE_RATE` double DEFAULT NULL,
  `SELF` varchar(50) DEFAULT NULL,
  `BARCODE` varchar(50) DEFAULT NULL,
  `SUPPLIER_ID` int(11) DEFAULT NULL,
  PRIMARY KEY (`STOCK_ID`),
  KEY `FK_STOCK_INVOICE` (`INVOICE_ID`),
  KEY `FK_STOCK_ITEM` (`ITEM_ID`),
  KEY `FK_STOCK_PHARMACY` (`PHARMACY_ID`),
  KEY `FK_STOCK_SUPPLIER_idx` (`SUPPLIER_ID`),
  CONSTRAINT `FK_STOCK_INVOICE` FOREIGN KEY (`INVOICE_ID`) REFERENCES `invoice` (`INVOICE_ID`) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT `FK_STOCK_ITEM` FOREIGN KEY (`ITEM_ID`) REFERENCES `items` (`ITEM_ID`) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT `FK_STOCK_PHARMACY` FOREIGN KEY (`PHARMACY_ID`) REFERENCES `pharmacy` (`PHARMACY_ID`) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT `FK_STOCK_SUPPLIER` FOREIGN KEY (`SUPPLIER_ID`) REFERENCES `supplier` (`SUPPLIER_ID`)
) ;



DROP TABLE IF EXISTS `tax`;

CREATE TABLE `tax` (
  `TAX_ID` int(11) NOT NULL AUTO_INCREMENT,
  `TAX_CD` varchar(20) DEFAULT NULL,
  `TAX_DESC` varchar(200) DEFAULT NULL,
  `PERCENTAGE` float DEFAULT NULL,
  `CREATION_TS` timestamp NULL DEFAULT NULL,
  `CREATION_USER_ID` varchar(50) DEFAULT NULL,
  `LAST_UPDATE_TS` timestamp NULL DEFAULT NULL,
  `LAST_UPDATE_USER_ID` varchar(50) DEFAULT NULL,
  `AUDIT_ID` int(11) DEFAULT NULL,
  PRIMARY KEY (`TAX_ID`)
);


DROP TABLE IF EXISTS `temp_employee`;

CREATE TABLE `temp_employee` (
  `EMPLOYEE_ID` int(11) NOT NULL AUTO_INCREMENT,
  `PHONE_NBR` varchar(20) DEFAULT NULL,
  `TITLE` varchar(5) DEFAULT NULL,
  `FIRST_NM` varchar(50) NOT NULL,
  `MIDDLE_NM` varchar(50) DEFAULT NULL,
  `LAST_NM` varchar(50) NOT NULL,
  `GENDER_CD` char(1) DEFAULT NULL,
  `DOB_DT` date DEFAULT NULL,
  `DATE_OF_JOINING` date DEFAULT NULL,
  `EMAIL_ID` varchar(50) DEFAULT NULL,
  `DESIGNATION_NM` varchar(250) DEFAULT NULL,
  `BIOGRAPHY_DESC` varchar(5000) DEFAULT NULL,
  `ADDRESS_LINE1` varchar(250) DEFAULT NULL,
  `ADDRESS_LINE2` varchar(250) DEFAULT NULL,
  `CITY_NM` varchar(50) DEFAULT NULL,
  `BLOOD_GROUP` varchar(20) DEFAULT NULL,
  `ARE_YOU_WORK_ON_SHIFTS` char(2) DEFAULT NULL,
  `POSTAL_CD` varchar(20) DEFAULT NULL,
  `CREATION_TS` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `CREATION_USER_ID` varchar(50) NOT NULL,
  `LAST_UPDATE_TS` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00',
  `LAST_UPDATE_USER_ID` varchar(50) DEFAULT NULL,
  `PROFILE_IMAGE` blob,
  `AUDIT_ID` int(11) DEFAULT NULL,
  `EMPLOYEE_TYPE_LOOKUP_ID` int(11) DEFAULT NULL,
  `PHARMACY_ID` int(11) DEFAULT NULL,
  `SALARY` double DEFAULT NULL,
  `EMPLOYEE_TYPE_FULL_PART_TIME` varchar(50) DEFAULT NULL,
  `COUNTRY_ID` int(11) DEFAULT NULL,
  `PROVINCES_ID` int(11) DEFAULT NULL,
  `ACTIVE_S` char(1) CHARACTER SET latin1 COLLATE latin1_swedish_ci DEFAULT 'Y',
  `EMPLOYEE_CD` varchar(20) DEFAULT NULL,
  `KRA_PIN` varchar(20) DEFAULT NULL,
  `IDENTIFICATION_DOCUMENT` blob,
  `NHIF_NO` varchar(20) DEFAULT NULL,
  `POLICE_GOOD_CONDUCT_CERTIFICATE` blob,
  `RESUME` blob,
  `SIGNED_CONTRACT` blob,
  `LANDLINE_NUMBER` varchar(20) DEFAULT NULL,
  `POST_BOX` varchar(20) DEFAULT NULL,
  `IDENTIFICATION_NO` varchar(20) DEFAULT NULL,
  `NSSF_NO` varchar(20) DEFAULT NULL,
  PRIMARY KEY (`EMPLOYEE_ID`),
  KEY `FK_TEMP_EMPLOYEE_COUNTRY_LOOKUP` (`COUNTRY_ID`),
  KEY `FK_TEMP_EMPLOYEE_EMPLOYEE_TYPE_LOOKUP` (`EMPLOYEE_TYPE_LOOKUP_ID`),
  KEY `FK_TEMP_EMPLOYEE_PROVINCES_LOOKUP` (`PROVINCES_ID`),
  CONSTRAINT `FK_TEMP_EMPLOYEE_COUNTRY_LOOKUP` FOREIGN KEY (`COUNTRY_ID`) REFERENCES `country_lookup` (`COUNTRY_ID`) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT `FK_TEMP_EMPLOYEE_EMPLOYEE_TYPE_LOOKUP` FOREIGN KEY (`EMPLOYEE_TYPE_LOOKUP_ID`) REFERENCES `employee_type_lookup` (`EMPLOYEE_TYPE_LOOKUP_ID`) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT `FK_TEMP_EMPLOYEE_PROVINCES_LOOKUP` FOREIGN KEY (`PROVINCES_ID`) REFERENCES `provinces_lookup` (`PROVINCES_ID`) ON DELETE RESTRICT ON UPDATE RESTRICT
) ;


DROP TABLE IF EXISTS `temp_employee_education`;

CREATE TABLE `temp_employee_education` (
  `EMPLOYEE_EDUCATION_ID` int(11) NOT NULL AUTO_INCREMENT,
  `EMPLOYEE_ID` int(11) NOT NULL,
  `STUDIED_AT` varchar(250) DEFAULT NULL,
  `DEGREE` varchar(250) DEFAULT NULL,
  `GARDUATION_DATE` date DEFAULT NULL,
  `CREATION_TS` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `CREATION_USER_ID` varchar(50) NOT NULL,
  `LAST_UPDATE_TS` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00',
  `LAST_UPDATE_USER_ID` varchar(50) DEFAULT NULL,
  `AUDIT_ID` int(11) DEFAULT NULL,
  `CERTIFICATE` blob,
  PRIMARY KEY (`EMPLOYEE_EDUCATION_ID`),
  KEY `FK_TEMP_EMPLOYEE_EDUCATION_PVDR` (`EMPLOYEE_ID`),
  CONSTRAINT `FK_TEMP_EMPLOYEE_EDUCATION_EMPLOYEE` FOREIGN KEY (`EMPLOYEE_ID`) REFERENCES `temp_employee` (`EMPLOYEE_ID`) ON DELETE RESTRICT ON UPDATE RESTRICT
) ;



DROP TABLE IF EXISTS `temp_employee_honor`;

CREATE TABLE `temp_employee_honor` (
  `EMPLOYEE_HONOR_ID` int(11) NOT NULL AUTO_INCREMENT,
  `EMPLOYEE_ID` int(11) NOT NULL,
  `HONOR_NM` varchar(250) DEFAULT NULL,
  `HONOR_DESC` varchar(250) DEFAULT NULL,
  `RECEIVE_DT` date DEFAULT NULL,
  `CREATION_TS` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `CREATION_USER_ID` varchar(50) NOT NULL,
  `LAST_UPDATE_TS` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00',
  `LAST_UPDATE_USER_ID` varchar(50) DEFAULT NULL,
  `AUDIT_ID` int(11) DEFAULT NULL,
  PRIMARY KEY (`EMPLOYEE_HONOR_ID`),
  KEY `FK_TEMP_EMPLOYEE_HONOR_PVDR` (`EMPLOYEE_ID`),
  CONSTRAINT `FK_TEMP_EMPLOYEE_HONOR_EMPLOYEE` FOREIGN KEY (`EMPLOYEE_ID`) REFERENCES `temp_employee` (`EMPLOYEE_ID`) ON DELETE RESTRICT ON UPDATE RESTRICT
) ;


DROP TABLE IF EXISTS `temp_employee_interest`;

CREATE TABLE `temp_employee_interest` (
  `EMPLOYEE_INTEREST_ID` int(11) NOT NULL AUTO_INCREMENT,
  `EMPLOYEE_ID` int(11) NOT NULL,
  `AREA_OF_INTEREST_DESC` varchar(250) DEFAULT NULL,
  `CREATION_TS` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `CREATION_USER_ID` varchar(50) NOT NULL,
  `LAST_UPDATE_TS` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00',
  `LAST_UPDATE_USER_ID` varchar(50) DEFAULT NULL,
  `INTRESTED_AT` varchar(250) DEFAULT NULL,
  `AUDIT_ID` int(11) DEFAULT NULL,
  PRIMARY KEY (`EMPLOYEE_INTEREST_ID`),
  KEY `FK_TEMP_EMPLOYEE_INTEREST_PVDR` (`EMPLOYEE_ID`),
  CONSTRAINT `FK_TEMP_EMPLOYEE_INTREST_EMPLOYEE` FOREIGN KEY (`EMPLOYEE_ID`) REFERENCES `temp_employee` (`EMPLOYEE_ID`) ON DELETE RESTRICT ON UPDATE RESTRICT
) ;



DROP TABLE IF EXISTS `temp_employee_prof_membership`;

CREATE TABLE `temp_employee_prof_membership` (
  `EMPLOYEE_PROF_MEMBERSHIP_ID` int(11) NOT NULL AUTO_INCREMENT,
  `EMPLOYEE_ID` int(11) NOT NULL,
  `MEMBERSHIP_NM` varchar(250) DEFAULT NULL,
  `START_DT` date DEFAULT NULL,
  `END_DT` date DEFAULT NULL,
  `CREATION_TS` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `CREATION_USER_ID` varchar(50) NOT NULL,
  `LAST_UPDATE_TS` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00',
  `LAST_UPDATE_USER_ID` varchar(50) DEFAULT NULL,
  `AUDIT_ID` int(11) DEFAULT NULL,
  PRIMARY KEY (`EMPLOYEE_PROF_MEMBERSHIP_ID`),
  KEY `FK_TEMP_EMPLOYEE_PROF_MEMBERSHIP_PVDR` (`EMPLOYEE_ID`),
  CONSTRAINT `FK_TEMP_EMPLOYEE_PROF_MEMBERSHIP_EMPLOYEE` FOREIGN KEY (`EMPLOYEE_ID`) REFERENCES `temp_employee` (`EMPLOYEE_ID`) ON DELETE RESTRICT ON UPDATE RESTRICT
) ;



DROP TABLE IF EXISTS `temp_employee_publication`;


CREATE TABLE `temp_employee_publication` (
  `EMPLOYEE_PUBLICATION_ID` int(11) NOT NULL AUTO_INCREMENT,
  `EMPLOYEE_ID` int(11) NOT NULL,
  `PUBLICATION_NM` varchar(250) DEFAULT NULL,
  `PUBLICATION_DESC` varchar(250) DEFAULT NULL,
  `PUBLISH_DT` date DEFAULT NULL,
  `CREATION_TS` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `CREATION_USER_ID` varchar(50) NOT NULL,
  `LAST_UPDATE_TS` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00',
  `LAST_UPDATE_USER_ID` varchar(50) DEFAULT NULL,
  `AUDIT_ID` int(11) DEFAULT NULL,
  PRIMARY KEY (`EMPLOYEE_PUBLICATION_ID`),
  KEY `FK_TEMP_EMPLOYEE_PUBLICATION_PVDR` (`EMPLOYEE_ID`),
  CONSTRAINT `FK_TEMP_EMPLOYEE_PUBLICATION_EMPLOYEE` FOREIGN KEY (`EMPLOYEE_ID`) REFERENCES `temp_employee` (`EMPLOYEE_ID`) ON DELETE RESTRICT ON UPDATE RESTRICT
);



DROP TABLE IF EXISTS `temp_employee_salary`;

CREATE TABLE `temp_employee_salary` (
  `EMPLOYEE_SALARY_ID` int(11) NOT NULL AUTO_INCREMENT,
  `AUDIT_ID` int(11) DEFAULT NULL,
  `EMPLOYEE_ID` int(11) DEFAULT NULL,
  `CREATION_TS` timestamp NULL DEFAULT NULL,
  `CREATION_USER_ID` varchar(50) DEFAULT NULL,
  `LAST_UPDATE_TS` timestamp NULL DEFAULT NULL,
  `LAST_UPDATE_USER_ID` varchar(50) DEFAULT NULL,
  `SALARY_DT` date DEFAULT NULL,
  `BASIC` double DEFAULT NULL,
  `HRA` double DEFAULT NULL,
  `DA` double DEFAULT NULL,
  `MEDICAL` double DEFAULT NULL,
  `P_TAX` double DEFAULT NULL,
  `PF_EMPLOYEE` double DEFAULT NULL,
  `PF_EMPLOYER` double DEFAULT NULL,
  `TDS` double DEFAULT NULL,
  `ESI` double DEFAULT NULL,
  `GROSS_SALARY` double DEFAULT NULL,
  PRIMARY KEY (`EMPLOYEE_SALARY_ID`),
  KEY `FK_TEMP_EMPLOYEE_SALARY_EMPLOYEE` (`EMPLOYEE_ID`),
  CONSTRAINT `FK_TEMP_EMPLOYEE_SALARY_EMPLOYEE` FOREIGN KEY (`EMPLOYEE_ID`) REFERENCES `temp_employee` (`EMPLOYEE_ID`) ON DELETE RESTRICT ON UPDATE RESTRICT
) ;


DROP TABLE IF EXISTS `temp_employment_history`;

CREATE TABLE `temp_employment_history` (
  `EMPLOYMENT_HISTORY_ID` int(11) NOT NULL AUTO_INCREMENT,
  `COMPANY_NAME` varchar(100) NOT NULL,
  `START_DT` date DEFAULT NULL,
  `END_DT` date DEFAULT NULL,
  `COMPANY_ADDRESS` varchar(250) DEFAULT NULL,
  `REPORTING_PERSON_DETAILS` varchar(50) DEFAULT NULL,
  `MANAGER_NM` varchar(50) DEFAULT NULL,
  `MANAGER_PHONE_NBR` varchar(20) DEFAULT NULL,
  `MANAGER_EMAIL_ID` varchar(50) DEFAULT NULL,
  `DESIGNATION` varchar(50) DEFAULT NULL,
  `EMPLOYMENT_TYPE` varchar(50) DEFAULT NULL,
  `REFERENCE1` varchar(50) DEFAULT NULL,
  `REFERENCE2` varchar(50) DEFAULT NULL,
  `CREATION_TS` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `CREATION_USER_ID` varchar(50) NOT NULL,
  `LAST_UPDATE_TS` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00',
  `LAST_UPDATE_USER_ID` varchar(50) DEFAULT NULL,
  `AUDIT_ID` int(11) DEFAULT NULL,
  `EMPLOYEE_ID` int(11) DEFAULT NULL,
  PRIMARY KEY (`EMPLOYMENT_HISTORY_ID`),
  KEY `FK_TEMP_EMPLOYMENT_HISTORY_EMPLOYEE` (`EMPLOYEE_ID`),
  CONSTRAINT `FK_TEMP_EMPLOYMENT_HISTORY_EMPLOYEE` FOREIGN KEY (`EMPLOYEE_ID`) REFERENCES `temp_employee` (`EMPLOYEE_ID`) ON DELETE RESTRICT ON UPDATE RESTRICT
) ;



DROP TABLE IF EXISTS `unit_of_measurement`;

CREATE TABLE `unit_of_measurement` (
  `UNIT_OF_MEASUREMENT_ID` int(11) NOT NULL AUTO_INCREMENT,
  `MEASUREMENT_CD` varchar(20) DEFAULT NULL,
  `MEASUREMENT_NAME` varchar(100) DEFAULT NULL,
  `MEASUREMENT_DESC` mediumtext CHARACTER SET latin1 COLLATE latin1_swedish_ci,
  `ACTIVE_S` char(1) CHARACTER SET latin1 COLLATE latin1_swedish_ci DEFAULT 'Y',
  `CREATION_TS` timestamp NULL DEFAULT NULL,
  `CREATION_USER_ID` varchar(50) DEFAULT NULL,
  `LAST_UPDATE_TS` timestamp NULL DEFAULT NULL,
  `LAST_UPDATE_USER_ID` varchar(50) DEFAULT NULL,
  `AUDIT_ID` int(11) DEFAULT NULL,
  PRIMARY KEY (`UNIT_OF_MEASUREMENT_ID`)
) ;


DROP TABLE IF EXISTS `user_roles`;

CREATE TABLE `user_roles` (
  `USER_ROLES_ID` int(11) NOT NULL AUTO_INCREMENT,
  `USER_ID` int(11) DEFAULT NULL,
  `ROLE_ID` int(11) DEFAULT NULL,
  `CREATION_TS` timestamp NULL DEFAULT NULL,
  `CREATION_USER_ID` varchar(50) DEFAULT NULL,
  `LAST_UPDATE_TS` timestamp NULL DEFAULT NULL,
  `LAST_UPDATE_USER_ID` varchar(50) DEFAULT NULL,
  `AUDIT_ID` int(11) DEFAULT NULL,
  PRIMARY KEY (`USER_ROLES_ID`),
  KEY `FK_USER_ROLE_USERS` (`USER_ID`),
  KEY `FK_USER_ROLE_ROLES` (`ROLE_ID`),
  CONSTRAINT `FK_USER_ROLE_ROLES` FOREIGN KEY (`ROLE_ID`) REFERENCES `roles` (`ROLE_ID`) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT `FK_USER_ROLE_USERS` FOREIGN KEY (`USER_ID`) REFERENCES `users` (`USER_ID`) ON DELETE RESTRICT ON UPDATE RESTRICT
);



DROP TABLE IF EXISTS `users`;


CREATE TABLE `users` (
  `USER_ID` int(11) NOT NULL AUTO_INCREMENT,
  `USER_NM` varchar(50) DEFAULT NULL,
  `PASSWORD` varchar(50) DEFAULT NULL,
  `CREATION_TS` timestamp NULL DEFAULT NULL,
  `CREATION_USER_ID` varchar(50) DEFAULT NULL,
  `LAST_UPDATE_TS` timestamp NULL DEFAULT NULL,
  `LAST_UPDATE_USER_ID` varchar(50) DEFAULT NULL,
  `AUDIT_ID` int(11) DEFAULT NULL,
  PRIMARY KEY (`USER_ID`)
) ;
