
DROP PROCEDURE IF EXISTS `SP_REPORT_TEST4`;
CREATE DEFINER=`ihealthpharm`@`%` PROCEDURE `SP_REPORT_TEST4`(
	IN `WHERECLAUSE` VARCHAR(3000)
)
BEGIN

DECLARE BASE_SQL  VARCHAR(5000) DEFAULT '';

SET BASE_SQL=  'SELECT 
  i.ITEM_NM, 
  si.SALE_QTY TOTAL_QTY, 
  si.UNIT_SALE_PRICE MRP, 
  si.VAT EFFECTIVE_VAT,
  s.TOTAL_QTY,
  s.OVERALL_DISCOUNT,
  s.TOTAL_AMOUNT,
  si.VAT,
  s.BILL_CODE,
  s.CUSTOMER_NM,
  si.SALE_AMOUNT  
  FROM sales s 
INNER JOIN sales_items si ON s.BILL_ID = si.BILL_ID
INNER JOIN items i ON i.ITEM_ID = si.ITEM_ID ';


SET @FINAL_SQL= CONCAT(BASE_SQL,WHERECLAUSE);

PREPARE stmt FROM @FINAL_SQL;
EXECUTE  stmt;
deallocate PREPARE stmt;


END