CREATE TABLE `stock_tmp` (
`ITEM_ID` int(11) DEFAULT NULL,
`PACK` varchar(20) DEFAULT NULL,
`UNIT_PURCHASE_RATE` double DEFAULT NULL,
`PURCHASE_DISCOUNT_PERCENTAGE` double DEFAULT NULL,
`UNIT_SALE_RATE` double DEFAULT NULL,
`SALE_DISCOUNT_PERCENTAGE` double DEFAULT NULL,
`STOCK_ID` int(11)
);
